Repository centreon/centreon-documentation, pull requests merged in 2020-07, with the labels that each got.

#242 doc(http): explain how to enable http2 on Centreon Web
  en/administration/secure-platform.md
  fr/administration/secure-platform.md
Labels: area/backend

#268 fix(index): correct indexes and add missing indexes
  en/integrations/plugin-packs/procedures/applications-salesforces-restapi.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/applications-salesforces-restapi.md
  fr/sidebars.json
Labels: bug

#260 enh(security): fix TLS protocol and cipher
  en/administration/secure-platform.md
  fr/administration/secure-platform.md
Labels: documentation
