Repository centreon/centreon-documentation, pull requests merged in 2020-11, with the labels that each got.

#389 feat(alerts/notifs): add filter management chapter to events view
  en/alerts-notifications/events-view.md
  en/assets/alerts/events-view/manage-filters.gif
  fr/alerts-notifications/events-view.md
  fr/assets/alerts/events-view/manage-filters.gif
Labels: 20.04

#418 fix(release): wrong heading level
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#437 add(epp)cisco-cts-and-cyberpower-proc
  en/integrations/plugin-packs/procedures/hardware-devices-cisco-cts-snmp.md
  en/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/hardware-devices-cisco-cts-snmp.md
  fr/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md
  fr/sidebars.json
Labels: 20.04, 20.10, approved-but-do-not-merge, pack-monitoring-proc

#439 Fix link ha migration
  en/administration/centreon-ha/upgrade-from-centreon-failover.md
  fr/administration/centreon-ha/upgrade-from-centreon-failover.md
Labels: 20.04, 20.10

#433 add(epp): Graylog monitoring procedure
  en/integrations/plugin-packs/procedures/applications-graylog-restapi.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/applications-graylog-restapi.md
  fr/sidebars.json
Labels: 20.04, 20.10, approved-but-do-not-merge, pack-monitoring-proc

#434 add(epp): Aws Ses monitoring procedure
  en/integrations/plugin-packs/procedures/cloud-aws-ses.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/cloud-aws-ses.md
  fr/sidebars.json
Labels: 20.04, 20.10, approved-but-do-not-merge, pack-monitoring-proc

#430 add(epp): Alyvix Server monitoring procedure
  en/integrations/plugin-packs/procedures/applications-monitoring-alyvix-restapi.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/applications-monitoring-alyvix-restapi.md
  fr/sidebars.json
Labels: 20.04, 20.10, approved-but-do-not-merge, pack-monitoring-proc

#438 fix(license upload):disable mod_security
  en/administration/secure-platform.md
  fr/administration/secure-platform.md
Labels: area/backend

#446 Fix(anomaly) remove master redhat ha documentation paragraph
  en/administration/centreon-ha/installation-2-nodes.md
  fr/administration/centreon-ha/installation-2-nodes.md
Labels: documentation

#442 add(epp): cisco firepower snmp
  en/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
  fr/sidebars.json
Labels: 20.04, 20.10

#416 release(autodiscovery): prepare 20.04.6 release notes
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.04

#452 enh(release): prepare broker 20.10.1 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#453 enh(release): prepare broker 20.04.10 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#467 enh(security): disable http trace option in http configuration
  en/administration/secure-platform.md
  fr/administration/secure-platform.md
Labels: 20.10, area/backend
