Repository centreon/centreon-documentation, pull requests merged in 2021-11, with the labels that each got.

#1121 Prepare 21.10.0 rn
  en/releases/centreon-commercial-extensions.md
  en/releases/centreon-core.md
  en/releases/centreon-os-extensions.md
  en/releases/introduction.md
  fr/releases/centreon-commercial-extensions.md
  fr/releases/centreon-core.md
  fr/releases/centreon-os-extensions.md
  fr/releases/introduction.md
Labels: 21.10

#1049 Doc about upgrading to 21.10
  en/graph-views/upgrade.md
  en/releases/introduction.md
  en/reporting/upgrade.md
  en/service-mapping/upgrade.md
  en/update/update-centreon-platform.md
  en/upgrade/introduction.md
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-20-04.md
  en/upgrade/upgrade-from-20-10.md
  en/upgrade/upgrade-from-21-04.md
  en/upgrade/upgrade-from-3-4.md
  fr/graph-views/upgrade.md
  fr/reporting/upgrade.md
  fr/service-mapping/upgrade.md
  fr/sidebars.json
  fr/update/update-centreon-platform.md
  fr/upgrade/introduction.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-20-04.md
  fr/upgrade/upgrade-from-20-10.md
  fr/upgrade/upgrade-from-21-04.md
  fr/upgrade/upgrade-from-3-4.md
Labels: 21.10

#1143 fix(security): correct Apache HTTPS configuration for 21.10
  en/administration/secure-platform.md
  fr/administration/secure-platform.md
Labels: 21.10

#1144 fix(security): add missing Apache configuration
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-3-4.md
  fr/administration/secure-platform.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-3-4.md
Labels: 21.10

#1135 doc(release): add release note for Centreon Autodiscovery 21.04.2
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 21.04

#1145 enh(known-issues): add issue with missing translation
  en/resources/known-issues.md
  fr/resources/known-issues.md
Labels: 21.04, 21.10

#1133 Remove unnecessary parameter
  en/graph-views/secure-your-map-platform.md
  fr/graph-views/secure-your-map-platform.md
Labels: 20.04, 20.10, 21.04, 21.10

#1063 Prepare web 21.04.8
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#1064 enh(release): Add Centreon Web 20.10.13
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#959 Mon 10978 openid configuration examples
  en/administration/parameters/centreon-ui.md
  en/assets/administration/openid-connect-configuration.png
  fr/administration/parameters/centreon-ui.md
  fr/assets/administration/openid-connect-configuration.png
Labels: 21.04

#1160 doc(release): add release note for centreon-autodiscovery-21.10.1
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 21.10

#1164 doc(release): add release note for centreon-autodiscovery-21.04.3
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 21.04

#1171 enh(release): add Centreon Web 20.10.14 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#1065 enh(release): Add Centreon Web 20.04.20
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#1170 enh(release): add Centreon Web 21.04.9 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#1169 enh(release): add Centreon Web 21.10.1 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.10
