Repository centreon/centreon-documentation, pull requests merged in 2021-09, with the labels that each got.

#957 enh(epp): lenovo iomega snmp - typo
  en/integrations/plugin-packs/procedures/hardware-storage-lenovo-iomega-snmp.md
  fr/integrations/plugin-packs/procedures/hardware-storage-lenovo-iomega-snmp.md
Labels: pack-monitoring-proc

#958 add(epp): supermicro superdoctor snmp proc v2 - supermicro bmc snmp proc v2 - deprecate supermicro snmp
  en/integrations/plugin-packs/procedures/hardware-servers-supermicro-bmc-snmp.md
  en/integrations/plugin-packs/procedures/hardware-servers-supermicro-snmp.md
  en/integrations/plugin-packs/procedures/hardware-servers-supermicro-superdoctor-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/hardware-servers-supermicro-bmc-snmp.md
  fr/integrations/plugin-packs/procedures/hardware-servers-supermicro-snmp.md
  fr/integrations/plugin-packs/procedures/hardware-servers-supermicro-superdoctor-snmp.md
  fr/sidebars.json
Labels: pack-monitoring-proc

#960 add(epp): HashiCorp Vault RestAPI monit proc
  en/integrations/plugin-packs/procedures/applications-hashicorp-vault-restapi.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/applications-hashicorp-vault-restapi.md
  fr/sidebars.json
Labels: pack-monitoring-proc, next-release

#961 enh(release): Add Centreon Gorgone 21.0.4.2 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#962 enh(release): Add Centreon Gorgone 20.10.5 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#983 enh(release): Add Centreon Web 20.04.18 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#986 Fix cloud-prometheus-api
  en/integrations/plugin-packs/procedures/cloud-prometheus-api.md
Labels: pack-monitoring-proc

#982 enh(release): Add Centreon Web 20.10.11 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#981 enh(release): Add Centreon Web 21.04.5 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#1014 enh(release): Add Centreon MAP 20.10.5 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.10

#1033 enh(release): Add Centreon Gorgone 21.04.3 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#1032 enh(release): Add Centreon Anomaly Detection 21.04.1 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 21.04

#1029 enh(release): Add Centreon Web 20.04.19 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04
