Repository centreon/centreon-documentation, pull requests merged in 2021-06, with the labels that each got.

#763 enh(release): Prepare Centreon Web 20.04.14 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#785 enh(rn): prepare release notes for broker 20.04.14
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#796 enh(rn): prepare release notes for connectors 20.04.1
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#780 enh(release): prepare release notes for engine 20.04.12
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#784 enh(rn): prepare release notes for broker 20.10.5
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#795 enh(rn): prepare release notes for centreon connectors 20.10.1
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#779 enh(release): prepare engine 20.10.5 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#786 enh(rn): prepare release notes for centreon-broker 21.04.1
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#794 enh(rh): prepare release notes for centreon connectors 21.04.1
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#778 enh(rn): prepare release notes engine 21.04.2
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#787 add(mp) : add Cisco Wap snmp
  en/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#790 enh(epp): infoblox snmp - procedure v2
  en/integrations/plugin-packs/procedures/network-infoblox-snmp.md
  fr/integrations/plugin-packs/procedures/network-infoblox-snmp.md
Labels: next-release, pack-monitoring-proc

#791 add(epp): mobotix snmp - procedure v2
  en/integrations/plugin-packs/procedures/hardware-devices-camera-mobotix-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/hardware-devices-camera-mobotix-snmp.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#792 add(epp): Azure Discover monitoring procedure
  en/assets/integrations/plugin-packs/procedures/cloud-azure-management-discover-accessparameters.png
  en/assets/integrations/plugin-packs/procedures/cloud-azure-management-discover-credentials.png
  en/assets/integrations/plugin-packs/procedures/cloud-azure-management-discover-discoparameters.png
  en/assets/integrations/plugin-packs/procedures/cloud-azure-management-discover-provider.png
  en/assets/integrations/plugin-packs/procedures/cloud-azure-management-discover-results.png
  en/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-management-discover-accessparameters.png
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-management-discover-credentials.png
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-management-discover-discoparameters.png
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-management-discover-provider.png
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-management-discover-results.png
  fr/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
  fr/sidebars.json
Labels: pack-monitoring-proc

#797 feat(pack): update monproc_v2_nginx_serverstatus
  en/integrations/plugin-packs/procedures/applications-webservers-nginx-serverstatus.md
  fr/integrations/plugin-packs/procedures/applications-webservers-nginx-serverstatus.md
Labels: pack-monitoring-proc

#764 enh(release): Prepare Centreon Web 20.10.8 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#807 fix(traps): remove obsolete part
  en/monitoring/passive-monitoring/enable-snmp-traps.md
  fr/monitoring/passive-monitoring/enable-snmp-traps.md
Labels: 20.04, 20.10, 21.04, 21.10

#802 Update applications-protocol-modbus.md [EN]
  fr/integrations/plugin-packs/procedures/applications-protocol-modbus.md
Labels: pack-monitoring-proc

#804 feat(pack): monproc_v2_cisco_ucs_snmp
  en/integrations/plugin-packs/procedures/hardware-servers-cisco-ucs-snmp.md
  fr/integrations/plugin-packs/procedures/hardware-servers-cisco-ucs-snmp.md
Labels: pack-monitoring-proc

#806 add(epp): Azure Cache for Redis monitoring proc
  en/assets/integrations/plugin-packs/procedures/cloud-azure-database-redis-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-database-redis.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-database-redis-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-database-redis.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#808 enh(epp): hikvision snmp - procedure v2
  en/integrations/plugin-packs/procedures/hardware-devices-camera-hikvision-snmp.md
  fr/integrations/plugin-packs/procedures/hardware-devices-camera-hikvision-snmp.md
Labels: next-release, pack-monitoring-proc

#812 add(MP): Add Network TP-Link SNMP
  en/integrations/plugin-packs/procedures/network-tplink-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/network-tplink-snmp.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#817 add(mp)c advisor api monitoring procedure
  en/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#819 enh(epp): acme packet snmp - add acodec/policy-servers/security services
  en/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
  fr/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
Labels: next-release, pack-monitoring-proc

#826 add(mp): Azure CDN profile
  en/assets/integrations/plugin-packs/procedures/cloud-azure-network-cdn-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-network-cdn.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-network-cdn-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-network-cdn.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#827 add(mp): Azure Storage Sync
  en/assets/integrations/plugin-packs/procedures/cloud-azure-storage-storagesync-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-storage-storagesync.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-storage-storagesync-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-storage-storagesync.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#836 enh(release): Add Centreon Web 21.04.3 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#840 enh(rn): clarify the impact of autodiscovery 20.10.3 in the rn
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.10

#838 enh(release): Add Centreon Web 20.10.9 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10
