Repository centreon/centreon-documentation, pull requests merged in 2021-07, with the labels that each got.

#839 enh(release): Add Centreon Web 20.04.16 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#852 add(epp): centreon-nsclient tutorial
  en/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-configuration.png
  en/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-update.png
  en/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-webserver.png
  en/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-wizard1.png
  en/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-wizard2.png
  en/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-wizard3.png
  en/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-wizard4.png
  en/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-wizard5.png
  en/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-configuration.png
  fr/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-update.png
  fr/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-webserver.png
  fr/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-wizard1.png
  fr/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-wizard2.png
  fr/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-wizard3.png
  fr/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-wizard4.png
  fr/assets/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial-wizard5.png
  fr/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial.md
  fr/sidebars.json
Labels: pack-monitoring-proc

#854 Update applications-veeam-nsclient-05-restapi
  en/integrations/plugin-packs/procedures/applications-veeam-nsclient-05-restapi.md
Labels: pack-monitoring-proc

#855 Update applications-veeam-nsclient-05-restapi
  fr/integrations/plugin-packs/procedures/applications-veeam-nsclient-05-restapi.md
Labels: pack-monitoring-proc

#856 Enh(mp) azure management api add capacity mode
  en/integrations/plugin-packs/procedures/cloud-azure-management-apimanagement.md
  fr/integrations/plugin-packs/procedures/cloud-azure-management-apimanagement.md
Labels: enhancement, next-release, pack-monitoring-proc

#861 Prepare autodisco 20.10.4 rn
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.10

#862 Prepare broker 20.10.6 / engine 20.10.6 / clib 20.10.3 / connectors 20.10.2 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#857 enh(release): release notes for centreon-autodiscovery 21.04.1
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 21.04

#876 fix(sidebars) monitoring procedure issues
  en/sidebars.json
  fr/sidebars.json
Labels: pack-monitoring-proc

#870 Prepare poller 21.04.2-3 rn
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#881 fix(mp) align mp with sidebars
  en/integrations/plugin-packs/procedures/applications-exchange-nrpe.md
  en/integrations/plugin-packs/procedures/applications-exchange-nsclient-restapi.md
  en/integrations/plugin-packs/procedures/network-switchs-dell-xseries-snmp.md
  fr/integrations/plugin-packs/procedures/applications-exchange-nrpe.md
  fr/integrations/plugin-packs/procedures/applications-exchange-nsclient-restapi.md
  fr/integrations/plugin-packs/procedures/network-switchs-dell-xseries-snmp.md
Labels: pack-monitoring-proc

#860 Prepare autodisco 20.04.9 rn
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.04

#883 fix(pack)remove-outdated-monitoring-procedure
  en/integrations/plugin-packs/procedures/applications-github-http.md
  fr/integrations/plugin-packs/procedures/applications-github-http.md
Labels: pack-monitoring-proc

#871 Add(ha guide) add recette guide centreon ha
  en/administration/centreon-ha/acceptance-guide.md
  en/sidebars.json
  fr/administration/centreon-ha/acceptance-guide.md
  fr/sidebars.json
Labels: documentation, enhancement

#879 fix(mp) blockchain Packs with no monitoring procedure
  en/integrations/plugin-packs/procedures/blockchain-hyperledger-exporter.md
  en/integrations/plugin-packs/procedures/blockchain-parity-ethpoller-restapi.md
  en/integrations/plugin-packs/procedures/blockchain-parity-restapi.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/blockchain-hyperledger-exporter.md
  fr/integrations/plugin-packs/procedures/blockchain-parity-ethpoller-restapi.md
  fr/integrations/plugin-packs/procedures/blockchain-parity-restapi.md
  fr/sidebars.json
Labels: pack-monitoring-proc

#893 Enh(doc)dedicated plugins troubleshooting page
  en/integrations/plugin-packs/tutorials/troubleshooting-plugins.md
  en/sidebars.json
Labels: enhancement

#872 enh(mp): Squid SNMP
  en/integrations/plugin-packs/procedures/applications-squid-snmp.md
  fr/integrations/plugin-packs/procedures/applications-squid-snmp.md
Labels: enhancement, pack-monitoring-proc

#873 enh(mp): ClamAV SSH
  en/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
  fr/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
Labels: enhancement, pack-monitoring-proc

#904 enh(doc) deprecating old NetApp Packs
  en/integrations/plugin-packs/procedures/hardware-storage-netapp-restapi.md
  en/integrations/plugin-packs/procedures/hardware-storage-netapp-snmp.md
  fr/integrations/plugin-packs/procedures/hardware-storage-netapp-restapi.md
  fr/integrations/plugin-packs/procedures/hardware-storage-netapp-snmp.md
Labels: enhancement

#906 add(epp): aruba aoscx snmp proc
  en/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
  fr/sidebars.json
Labels: pack-monitoring-proc

#898 enh(release): Add Centreon Web 20.04.17 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#897 enh(release): Add Centreon Web 20.10.10 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#896 enh(release): Add Centreon Web 21.04.4 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04
