Repository centreon/centreon-documentation, pull requests merged in 2021-05, with the labels that each got.

#706 enh(release): Add Centreon MAP 20.10.4 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.10

#718 add(epp): huawei oceanstor snmp proc
  en/integrations/plugin-packs/procedures/hardware-storage-huawei-oceanstor-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/hardware-storage-huawei-oceanstor-snmp.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#691 add(epp): bdt multistak snmp
  en/integrations/plugin-packs/procedures/hardware-storage-bdt-multistak-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/hardware-storage-bdt-multistak-snmp.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#694 Enh(mp) add new aix ssh monitoring procedure
  en/integrations/plugin-packs/procedures/operatingsystems-aix-ssh.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/operatingsystems-aix-ssh.md
  fr/sidebars.json
Labels: pack-monitoring-proc

#721 fix(upgrade): improve upgrade chapters
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-20-04.md
  en/upgrade/upgrade-from-3-4.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-20-04.md
  fr/upgrade/upgrade-from-3-4.md
Labels: 21.04

#719 add(epp): proxmox mg api proc
  en/integrations/plugin-packs/procedures/applications-proxmox-mg-api.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/applications-proxmox-mg-api.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#717 enh(ha)rewrite-architecture-introduction
  en/assets/integrations/centreon-ha/centreon-ha-2-nodes-arch.png
  en/assets/integrations/centreon-ha/centreon-ha-4-nodes-arch.png
  en/assets/integrations/centreon-ha/cluster-2-nodes-architecture.png
  en/assets/integrations/centreon-ha/cluster-2-nodes.png
  en/assets/integrations/centreon-ha/cluster_resources_desc.png
  en/assets/integrations/centreon-ha/cluster_services_desc.png
  en/installation/installation-of-centreon-ha/architecture.md
  en/installation/installation-of-centreon-ha/installation-2-nodes.md
  en/installation/installation-of-centreon-ha/installation-4-nodes.md
  en/installation/installation-of-centreon-ha/overview.md
  en/sidebars.json
Labels: enhancement

#703 enh(release): add License Manager 20.10.3 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.10

#702 enh(release): add License Manager 20.04.5 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.04

#728 conf(apache): avoid 404 redirection on react routes
  en/administration/secure-platform.md
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-3-4.md
  fr/administration/secure-platform.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-3-4.md
Labels: area/backend

#710 enh(release): Add Centreon MBI 20.10.2 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.10

#730 change github url to match new organization
  en/integrations/stream-connectors/sc-service-now.md
  en/integrations/stream-connectors/sc-splunk-events.md
  en/integrations/stream-connectors/sc-splunk-metrics.md
  fr/integrations/stream-connectors/sc-service-now.md
  fr/integrations/stream-connectors/sc-splunk-events.md
  fr/integrations/stream-connectors/sc-splunk-metrics.md
Labels: enhancement

#720 add(mp): Azure Application Insights
  en/assets/integrations/plugin-packs/procedures/cloud-azure-management-applicationinsights-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-management-applicationinsights.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-management-applicationinsights-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-management-applicationinsights.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#722 add(epp): Azure App Service Plan
  en/assets/integrations/plugin-packs/procedures/cloud-azure-web-appserviceplan-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-web-appserviceplan.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-web-appserviceplan-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-web-appserviceplan.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#724 fix(epp): Azure App GW monitoring proc provider URL fix
  en/integrations/plugin-packs/procedures/cloud-azure-network-appgateway.md
Labels: pack-monitoring-proc

#727 Add(mp): Azure API Management
  en/assets/integrations/plugin-packs/procedures/cloud-azure-management-apimanagement-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-management-apimanagement.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-management-apimanagement-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-management-apimanagement.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#729 fix(epp): Oracle plugin correct path [EN]
  en/integrations/plugin-packs/procedures/applications-databases-oracle.md
Labels: pack-monitoring-proc

#731 fix(epp): Oracle plugin correct path [FR]
  fr/integrations/plugin-packs/procedures/applications-databases-oracle.md
Labels: pack-monitoring-proc

#709 enh(release): Add Centreon MBI 20.04.5 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.04

#716 enh(doc): add message about logging out before upgrade
  en/update/update-centreon-ha.md
  en/update/update-centreon-platform.md
  en/upgrade/centreon-ha/upgrade-from-20.04.md
  en/upgrade/centreon-ha/upgrade-from-20.10.md
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-20-04.md
  en/upgrade/upgrade-from-20-10.md
  fr/update/update-centreon-ha.md
  fr/update/update-centreon-platform.md
  fr/upgrade/centreon-ha/upgrade-from-20.04.md
  fr/upgrade/centreon-ha/upgrade-from-20.10.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-20-04.md
  fr/upgrade/upgrade-from-20-10.md
Labels: 20.04, 20.10, 21.04, documentation

#697 enh(release): Add Centreon Web 20.10.7 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#696 enh(release): Add Centreon Web 20.04.13 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#726 add(epp): Azure Cosmos DB
  en/assets/integrations/plugin-packs/procedures/cloud-azure-database-cosmosdb-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-database-cosmosdb.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-database-cosmosdb-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-database-cosmosdb.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#735 fix(install): correct unattended.sh path
  en/installation/introduction.md
  fr/installation/introduction.md
Labels: 21.04

#739 enh(release): Add Centreon Web 21.04.1 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#746 fix(mp): Azure Application Insights
  en/integrations/plugin-packs/procedures/cloud-azure-management-applicationinsights.md
  fr/integrations/plugin-packs/procedures/cloud-azure-management-applicationinsights.md
Labels: next-release, pack-monitoring-proc

#725 enh(ha): add ha map 2 nodes
  en/graph-views/install-ha.md
Labels: enhancement

#745 add(mp): Azure Database for MySQL
  en/assets/integrations/plugin-packs/procedures/cloud-azure-database-mysql-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-database-mysql.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-database-mysql-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-database-mysql.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#749 fix(sidebars): Azure SQL Managed Instances & Application Insights entries
  en/sidebars.json
  fr/sidebars.json
Labels: pack-monitoring-proc

#751 enh(mp): HAProxy SNMP
  en/integrations/plugin-packs/procedures/applications-haproxy-snmp.md
  fr/integrations/plugin-packs/procedures/applications-haproxy-snmp.md
Labels: enhancement, pack-monitoring-proc

#756 enh(epp): Azure Application GW versions management
  en/integrations/plugin-packs/procedures/cloud-azure-network-appgateway.md
  fr/integrations/plugin-packs/procedures/cloud-azure-network-appgateway.md
Labels: pack-monitoring-proc

#758 enh(mp): SSH Protocol
  en/integrations/plugin-packs/procedures/applications-protocol-ssh.md
  fr/integrations/plugin-packs/procedures/applications-protocol-ssh.md
Labels: enhancement, pack-monitoring-proc

#744 enh(installation): make user read "Secure your platform" page
  en/installation/installation-of-a-central-server/using-virtual-machines.md
  en/installation/web-and-post-installation.md
  fr/installation/installation-of-a-central-server/using-virtual-machines.md
  fr/installation/web-and-post-installation.md
Labels: 21.04, 21.10

#774 chore(version): release notes for open tickets 20.10.2
  en/releases/centreon-os-extensions.md
  fr/releases/centreon-os-extensions.md
Labels: area/backend

#781 chore(version): release notes for open-tickets 20.04.2
  en/releases/centreon-os-extensions.md
  fr/releases/centreon-os-extensions.md
Labels: area/backend

#767 enh(doc)ha FR translation
  fr/assets/integrations/centreon-ha/centreon-ha-2-nodes-arch.png
  fr/assets/integrations/centreon-ha/centreon-ha-4-nodes-arch.png
  fr/assets/integrations/centreon-ha/cluster-2-nodes-architecture.png
  fr/assets/integrations/centreon-ha/cluster-2-nodes.png
  fr/assets/integrations/centreon-ha/cluster_resources_desc.png
  fr/assets/integrations/centreon-ha/cluster_services_desc.png
  fr/installation/installation-of-centreon-ha/installation-2-nodes.md
  fr/installation/installation-of-centreon-ha/installation-4-nodes.md
  fr/installation/installation-of-centreon-ha/overview.md
Labels: enhancement

#760 fix(security): FR typos in SELinux chapter
  fr/administration/secure-platform.md
Labels: enhancement

#770 (enh): add ha map 2 nodes FR
  fr/graph-views/install-ha.md
Labels: enhancement

#773 fix terms ha map 2 nodes-EN
  en/graph-views/install-ha.md
Labels: enhancement

#776 feat(pack): update monproc_v2_Aruba_Instant_SNMP_4
  en/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
  fr/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
Labels: enhancement, pack-monitoring-proc
