Repository centreon/centreon-documentation, pull requests merged in 2021-04, with the labels that each got.

#646 doc(dependencies): add openssl dependency in source install
  en/installation/installation-of-a-central-server/using-sources.md
  fr/installation/installation-of-a-central-server/using-sources.md
Labels: area/backend

#661 doc(broker): remove correlation module
  en/developer/developer-broker-mapping.md
  fr/developer/developer-broker-mapping.md
Labels: 21.04

#667 enh(install): fix centeron-release version
  en/graph-views/install.md
  en/graph-views/upgrade.md
  en/installation/installation-of-a-central-server/using-packages.md
  en/installation/installation-of-a-poller/using-packages.md
  en/installation/installation-of-a-remote-server/using-packages.md
  en/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-20-04.md
  en/upgrade/upgrade-from-20-10.md
  en/upgrade/upgrade-from-3-4.md
  fr/graph-views/install.md
  fr/graph-views/upgrade.md
  fr/installation/installation-of-a-central-server/using-packages.md
  fr/installation/installation-of-a-poller/using-packages.md
  fr/installation/installation-of-a-remote-server/using-packages.md
  fr/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-20-04.md
  fr/upgrade/upgrade-from-20-10.md
  fr/upgrade/upgrade-from-3-4.md
Labels: 21.04

#665 enh(install): add PHP7.3
  en/administration/centreon-ha/architecture.md
  en/administration/centreon-ha/installation-2-nodes.md
  en/administration/centreon-ha/installation-4-nodes.md
  en/administration/centreon-ha/operating-guide.md
  en/administration/database-partitioning.md
  en/administration/secure-platform.md
  en/installation/installation-of-a-central-server/using-centreon-iso.md
  en/installation/installation-of-a-central-server/using-packages.md
  en/installation/installation-of-a-central-server/using-sources.md
  en/installation/installation-of-a-remote-server/using-centreon-iso.md
  en/installation/installation-of-a-remote-server/using-packages.md
  en/installation/prerequisites.md
  en/reporting/installation.md
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-20-10.md
  en/upgrade/upgrade-from-3-4.md
  fr/administration/centreon-ha/architecture.md
  fr/administration/centreon-ha/installation-2-nodes.md
  fr/administration/centreon-ha/installation-4-nodes.md
  fr/administration/centreon-ha/operating-guide.md
  fr/administration/database-partitioning.md
  fr/administration/secure-platform.md
  fr/installation/installation-of-a-central-server/using-centreon-iso.md
  fr/installation/installation-of-a-central-server/using-packages.md
  fr/installation/installation-of-a-central-server/using-sources.md
  fr/installation/installation-of-a-remote-server/using-centreon-iso.md
  fr/installation/installation-of-a-remote-server/using-packages.md
  fr/installation/prerequisites.md
  fr/reporting/installation.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-20-10.md
  fr/upgrade/upgrade-from-3-4.md
Labels: 21.04

#671 fix(security): correct gorgone account name
  en/administration/secure-platform.md
  fr/administration/secure-platform.md
Labels: 20.04, 20.10, 21.04

#670 fix(upgrade): correct 20.10 21.04 upgrade
  en/upgrade/upgrade-from-20-10.md
  fr/upgrade/upgrade-from-20-10.md
Labels: 21.04

#673 Security add selinux fail2ban
  en/administration/secure-platform.md
  en/installation/installation-of-a-central-server/using-packages.md
  en/installation/installation-of-a-poller/using-packages.md
  en/installation/installation-of-a-remote-server/using-packages.md
  fr/administration/secure-platform.md
  fr/installation/installation-of-a-central-server/using-packages.md
  fr/installation/installation-of-a-poller/using-packages.md
  fr/installation/installation-of-a-remote-server/using-packages.md
Labels: 20.04, 20.10, 21.04

#561 fix(pack) wrong Plugin package name in Gsuite monitoring procedure (en)
  en/integrations/plugin-packs/procedures/applications-google-gsuite-api.md
Labels: pack-monitoring-proc

#560 fix(pack) wrong Plugin package name in Gsuite monitoring procedure (fr)
  fr/integrations/plugin-packs/procedures/applications-google-gsuite-api.md
Labels: pack-monitoring-proc

#663 secure-add-selinux
  en/administration/secure-platform.md
  fr/administration/secure-platform.md
Labels: 20.04, 21.04

#657 documentation: Add SQL Request on index_data in known inssue
  en/graph-views/known-issues.md
  en/resources/known-issues.md
  en/sidebars.json
  fr/graph-views/known-issues.md
  fr/resources/known-issues.md
  fr/sidebars.json
Labels: 20.04, 20.10, 21.04

#634 Add(mp): Azure DevTools App Configuration
  en/assets/integrations/plugin-packs/procedures/cloud-azure-devtools-appconfiguration-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-devtools-appconfiguration.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-devtools-appconfiguration-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-devtools-appconfiguration.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#635 Fix(mp): Azure Management Automation
  en/integrations/plugin-packs/procedures/cloud-azure-management-automation.md
  fr/integrations/plugin-packs/procedures/cloud-azure-management-automation.md
Labels: next-release, pack-monitoring-proc

#637 add(epp): Azure Front Door monitoring proc
  en/assets/integrations/plugin-packs/procedures/cloud-azure-network-frontdoor-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-network-frontdoor.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-network-frontdoor-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-network-frontdoor.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#638 fix(plugin)azure integration
  en/integrations/plugin-packs/procedures/cloud-azure-integration-eventgrid.md
Labels: pack-monitoring-proc

#639 add(pack): Azure SQL Managed Instance
  en/assets/integrations/plugin-packs/procedures/cloud-azure-database-sqlmanagedinstance-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-database-sqlmanagedinstance.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-database-sqlmanagedinstance-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-database-sqlmanagedinstance.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#647 add(mp): Azure App Service
  en/assets/integrations/plugin-packs/procedures/cloud-azure-web-appservice-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-web-appservice.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-web-appservice-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-web-appservice.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#650 add(epp): Azure Event Hubs monitoring proc
  en/assets/integrations/plugin-packs/procedures/cloud-azure-analytics-eventhubs-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-analytics-eventhubs.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-analytics-eventhubs-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-analytics-eventhubs.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#654 enh(epp): athonet epc snmp - add aggregate/apns services
  en/integrations/plugin-packs/procedures/network-athonet-epc-snmp.md
  fr/integrations/plugin-packs/procedures/network-athonet-epc-snmp.md
Labels: next-release, pack-monitoring-proc

#678 enh(epp): acmepacket snmp - procedure v2
  en/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
  fr/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
Labels: next-release, pack-monitoring-proc

#622 enh(vm): Remove OVF and Keep OVA only
  en/administration/centreon-ha/installation-2-nodes.md
  en/administration/centreon-ha/installation-4-nodes.md
  en/assets/installation/ova_vbox_use_hardware_clock.png
  en/getting-started/installation-first-steps.md
  en/installation/download.md
  en/installation/installation-of-a-central-server/using-virtual-machines.md
  fr/administration/centreon-ha/installation-2-nodes.md
  fr/assets/installation/ova_vbox_use_hardware_clock.png
  fr/getting-started/installation-first-steps.md
  fr/installation/download.md
  fr/installation/installation-of-a-central-server/using-virtual-machines.md
  website/pages/en/index.js
  website/pages/fr/index.js
Labels: 20.04, 20.10, 21.04

#651 add(mp): Azure Functions
  en/assets/integrations/plugin-packs/procedures/cloud-azure-compute-functions-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-compute-functions-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc

#672 Enh(pack)netwok firewall pfsense snmp metricsv2
  en/integrations/plugin-packs/procedures/network-firewalls-pfsense-snmp.md
  fr/integrations/plugin-packs/procedures/network-firewalls-pfsense-snmp.md
Labels: pack-monitoring-proc

#660 enh(anomaly): add new functionality
  en/assets/monitoring/anomaly/configure_analysis_01.png
  en/assets/monitoring/anomaly/configure_analysis_02.png
  en/monitoring/anomaly-detection.md
  fr/assets/monitoring/anomaly/configure_analysis_01.png
  fr/assets/monitoring/anomaly/configure_analysis_02.png
  fr/monitoring/anomaly-detection.md
Labels: 20.10, 21.04

#676 enh(pack)apps cisco ise restapi metricsv2
  en/integrations/plugin-packs/procedures/applications-cisco-ise-restapi.md
  fr/integrations/plugin-packs/procedures/applications-cisco-ise-restapi.md
Labels: pack-monitoring-proc

#668 enh(install): improve servers installation
  en/assets/monitoring/monitoring-servers/move_poller_conf_1.png
  en/assets/monitoring/monitoring-servers/move_poller_conf_2.png
  en/installation/installation-of-a-central-server/using-centreon-iso.md
  en/installation/installation-of-a-central-server/using-packages.md
  en/installation/installation-of-a-central-server/using-sources.md
  en/installation/installation-of-a-poller/using-centreon-iso.md
  en/installation/installation-of-a-poller/using-packages.md
  en/installation/installation-of-a-remote-server/using-centreon-iso.md
  en/installation/installation-of-a-remote-server/using-packages.md
  en/monitoring/monitoring-servers/move-poller.md
  en/sidebars.json
  fr/assets/monitoring/monitoring-servers/move_poller_conf_1.png
  fr/assets/monitoring/monitoring-servers/move_poller_conf_2.png
  fr/installation/installation-of-a-central-server/using-centreon-iso.md
  fr/installation/installation-of-a-central-server/using-packages.md
  fr/installation/installation-of-a-central-server/using-sources.md
  fr/installation/installation-of-a-poller/using-centreon-iso.md
  fr/installation/installation-of-a-poller/using-packages.md
  fr/installation/installation-of-a-remote-server/using-centreon-iso.md
  fr/installation/installation-of-a-remote-server/using-packages.md
  fr/monitoring/monitoring-servers/move-poller.md
  fr/sidebars.json
Labels: 21.04

#679 enh(discovery): documentation of new features in host discovery
  en/assets/monitoring/discovery/host-discovery-goto-results.png
  en/assets/monitoring/discovery/host-discovery-mappers-association.png
  en/assets/monitoring/discovery/host-discovery-mappers-concatenation.gif
  en/assets/monitoring/discovery/host-discovery-mappers-hostcategory-create.png
  en/assets/monitoring/discovery/host-discovery-mappers-hostcategory-select.png
  en/assets/monitoring/discovery/host-discovery-mappers-hostgroup-create.png
  en/assets/monitoring/discovery/host-discovery-mappers-hostgroup-select.png
  en/assets/monitoring/discovery/host-discovery-mappers-hostseverity-select.png
  en/assets/monitoring/discovery/host-discovery-mappers-property.png
  en/assets/monitoring/discovery/host-discovery-wizard-step-4.png
  en/monitoring/discovery/hosts-discovery.md
  fr/assets/monitoring/discovery/host-discovery-goto-results.png
  fr/assets/monitoring/discovery/host-discovery-mappers-association.png
  fr/assets/monitoring/discovery/host-discovery-mappers-concatenation.gif
  fr/assets/monitoring/discovery/host-discovery-mappers-hostcategory-create.png
  fr/assets/monitoring/discovery/host-discovery-mappers-hostcategory-select.png
  fr/assets/monitoring/discovery/host-discovery-mappers-hostgroup-create.png
  fr/assets/monitoring/discovery/host-discovery-mappers-hostgroup-select.png
  fr/assets/monitoring/discovery/host-discovery-mappers-hostseverity-select.png
  fr/assets/monitoring/discovery/host-discovery-mappers-property.png
  fr/assets/monitoring/discovery/host-discovery-wizard-step-4.png
  fr/monitoring/discovery/hosts-discovery.md
Labels: 21.04

#669 enh(pp): adding the instruction to install perl dependancy (MON-7111)
  en/integrations/plugin-packs/procedures/cloud-azure-compute-virtualmachine.md
  fr/integrations/plugin-packs/procedures/cloud-azure-compute-virtualmachine.md
Labels: 20.04, 20.10, 21.04

#681 fix(epp): Azure Event Hubs provider image EN
  en/integrations/plugin-packs/procedures/cloud-azure-analytics-eventhubs.md
Labels: pack-monitoring-proc

#683 enh(broker): add doc for new logs + deprecated old logs
  en/monitoring/monitoring-servers/advanced-configuration.md
  fr/monitoring/monitoring-servers/advanced-configuration.md
Labels: 21.04

#687 fix(pack) wrong Plugin package name in monitoring procedure
  en/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
  fr/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
Labels: pack-monitoring-proc

#695 enh(release): Add Centreon Engine 21.04.1 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#621 enh(release): prepare Engine 20.04.10 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#704 enh(release): add Centreon Broker 20.04.13 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#712 fix(anomaly): add missing repo for el7
  en/monitoring/anomaly-detection.md
  fr/monitoring/anomaly-detection.md
Labels: 20.04, 20.10, 21.04

#707 Prepare engine 20.04.11 rn
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#705 enh(release): add Centreon Broker 20.10.4 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#620 enh(release): prepare Engine 20.10.3 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#698 enh(release): Add Centreon BAM 20.04.7 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.04

#699 enh(release): Add Centreon BAM 20.10.3 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.10

#708 enh(release): Add Centreon Engine 20.10.4 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#700 enh(release): Add Centreon MBI 20.04.4 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.04

#701 enh(release): Add Centreon MBI 20.10.1 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.10

#714 enh(organization): change sidebar.json organization
  en/sidebars.json
  fr/sidebars.json
  fr/update/update-centreon-ha.md
Labels: enhancement

#652 Update network-firewalls-paloalto-standard-ssh.md
  fr/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-ssh.md
Labels: pack-monitoring-proc

#653 Update network-firewalls-paloalto-standard-ssh.md
  en/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-ssh.md
Labels: pack-monitoring-proc

#715 add(epp): Azure Application Gateway monitoring proc
  en/assets/integrations/plugin-packs/procedures/cloud-azure-network-appgateway-provider.png
  en/integrations/plugin-packs/procedures/cloud-azure-network-appgateway.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-network-appgateway-provider.png
  fr/integrations/plugin-packs/procedures/cloud-azure-network-appgateway.md
  fr/sidebars.json
Labels: next-release, pack-monitoring-proc
