Repository centreon/centreon-documentation, pull requests merged in 2021-12, with the labels that each got.

#1075 doc(release): add release note for Centreon Engine 20.04.14
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#1072 doc(release): add release note for Centreon Broker 20.04.17
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#1088 doc(release): add release note for Centreon Connector SSH 20.04.2
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#1089 doc(release): add release note for Centreon Connector Perl 20.04.2
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#1175 (integration) add signl4 documentation
  en/integrations/event-management/sc-signl4-events.md
  en/sidebars.json
  fr/integrations/event-management/sc-signl4-events.md
  fr/sidebars.json
Labels: integration

#1139 add(epp): DB2 proc
  en/integrations/plugin-packs/procedures/applications-databases-db2.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/applications-databases-db2.md
  fr/sidebars.json
Labels: pack-monitoring-proc, next-release

#1127 refactoring(epp): redis procedures
  en/integrations/plugin-packs/procedures/applications-databases-redis.md
  en/integrations/plugin-packs/procedures/applications-redis-cli.md
  en/integrations/plugin-packs/procedures/applications-redis-restapi.md
  en/integrations/plugin-packs/procedures/applications-redis-rlec-restapi.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/applications-databases-redis.md
  fr/integrations/plugin-packs/procedures/applications-redis-cli.md
  fr/integrations/plugin-packs/procedures/applications-redis-restapi.md
  fr/integrations/plugin-packs/procedures/applications-redis-rlec-restapi.md
  fr/sidebars.json
Labels: pack-monitoring-proc, next-release

#1151 add(epp): wallix bastion snmp proc
  en/integrations/plugin-packs/procedures/applications-wallix-bastion-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/applications-wallix-bastion-snmp.md
  fr/sidebars.json
Labels: pack-monitoring-proc, next-release

#1163 enh(mp): Open VPN OMI
  en/integrations/plugin-packs/procedures/applications-openvpn-omi.md
  fr/integrations/plugin-packs/procedures/applications-openvpn-omi.md
Labels: enhancement, pack-monitoring-proc

#1165 enh(mp): PHP FPM Web
  en/integrations/plugin-packs/procedures/applications-php-fpm-web.md
  fr/integrations/plugin-packs/procedures/applications-php-fpm-web.md
Labels: enhancement, pack-monitoring-proc

#1166 enh(mp): PHP APC Web
  en/integrations/plugin-packs/procedures/applications-php-apc-web.md
  fr/integrations/plugin-packs/procedures/applications-php-apc-web.md
Labels: enhancement, pack-monitoring-proc

#1176 add(epp): nvidia gpu smi ssh proc
  en/integrations/plugin-packs/procedures/hardware-devices-nvidia-gpu-smi-ssh.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/hardware-devices-nvidia-gpu-smi-ssh.md
  fr/sidebars.json
Labels: pack-monitoring-proc, next-release

#1180 add(pack): ericsson enmp api monitoring proc
  en/integrations/plugin-packs/procedures/applications-ericsson-enm-api.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/applications-ericsson-enm-api.md
  fr/sidebars.json
Labels: pack-monitoring-proc, next-release

#1185 add(epp): IBM TSAMP SSH proc
  en/integrations/plugin-packs/procedures/applications-ibm-tsamp-ssh.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/applications-ibm-tsamp-ssh.md
  fr/sidebars.json
Labels: pack-monitoring-proc, next-release

#1183 add(epp): gude epc pdu snmp proc
  en/integrations/plugin-packs/procedures/hardware-pdu-gude-epc-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/hardware-pdu-gude-epc-snmp.md
  fr/sidebars.json
Labels: pack-monitoring-proc, next-release

#1179 enh(release): Add Centreon PPM 20.10.2 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.10

#1162 fix(apache): disable mod security rule 200003
  en/administration/secure-platform.md
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-3-4.md
  fr/administration/secure-platform.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-3-4.md
Labels: area/backend

#1178 enh(release): Add Centreon PPM 21.04.1 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 21.04

#1177 doc(apache): update apache configuration
  en/administration/secure-platform.md
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-20-04.md
  en/upgrade/upgrade-from-20-10.md
  en/upgrade/upgrade-from-21-04.md
  en/upgrade/upgrade-from-3-4.md
  fr/administration/secure-platform.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-20-04.md
  fr/upgrade/upgrade-from-20-10.md
  fr/upgrade/upgrade-from-21-04.md
  fr/upgrade/upgrade-from-3-4.md
Labels: area/backend

#1186 fix(doc) typo in the name of the moxa plugin rpm
  en/integrations/plugin-packs/procedures/network-moxa-switch-snmp.md
  fr/integrations/plugin-packs/procedures/network-moxa-switch-snmp.md
Labels: pack-monitoring-proc

#1191 enh(release): Add Centreon Gorgone 21.10.1
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.10

#1192 enh(release): Add Centreon Gorgone 21.04.4
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#1193 enh(release): Add Centreon Gorgone 20.10.6
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#1198 chore(release): upgrade centreon release rpm
  en/graph-views/install.md
  en/graph-views/upgrade.md
  en/installation/installation-of-a-central-server/using-packages.md
  en/installation/installation-of-a-poller/using-packages.md
  en/installation/installation-of-a-remote-server/using-packages.md
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-20-04.md
  en/upgrade/upgrade-from-3-4.md
  fr/graph-views/install.md
  fr/graph-views/upgrade.md
  fr/installation/installation-of-a-central-server/using-packages.md
  fr/installation/installation-of-a-poller/using-packages.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-20-04.md
  fr/upgrade/upgrade-from-3-4.md
Labels: area/backend

#1196 chore(release): upgrade centreon release rpm (21.10)
  en/graph-views/install.md
  en/graph-views/upgrade.md
  en/health/centreon-agent.md
  en/installation/installation-of-a-central-server/using-packages.md
  en/installation/installation-of-a-central-server/using-sources.md
  en/installation/installation-of-a-poller/using-packages.md
  en/installation/installation-of-a-remote-server/using-packages.md
  en/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
  en/upgrade/centreon-ha/upgrade-from-20-04.md
  en/upgrade/centreon-ha/upgrade-from-20-10.md
  en/upgrade/centreon-ha/upgrade-from-21-04.md
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-20-04.md
  en/upgrade/upgrade-from-20-10.md
  en/upgrade/upgrade-from-21-04.md
  en/upgrade/upgrade-from-3-4.md
  fr/graph-views/install.md
  fr/graph-views/upgrade.md
  fr/health/centreon-agent.md
  fr/installation/installation-of-a-central-server/using-packages.md
  fr/installation/installation-of-a-central-server/using-sources.md
  fr/installation/installation-of-a-poller/using-packages.md
  fr/installation/installation-of-a-remote-server/using-packages.md
  fr/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
  fr/upgrade/centreon-ha/upgrade-from-20-04.md
  fr/upgrade/centreon-ha/upgrade-from-20-10.md
  fr/upgrade/centreon-ha/upgrade-from-21-04.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-20-04.md
  fr/upgrade/upgrade-from-20-10.md
  fr/upgrade/upgrade-from-21-04.md
  fr/upgrade/upgrade-from-3-4.md
Labels: area/backend

#1197 chore(release): upgrade centreon release rpm (21.04)
  en/graph-views/install.md
  en/graph-views/upgrade.md
  en/health/centreon-agent.md
  en/installation/installation-of-a-central-server/using-packages.md
  en/installation/installation-of-a-poller/using-packages.md
  en/installation/installation-of-a-remote-server/using-packages.md
  en/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
  en/upgrade/centreon-ha/upgrade-from-20.04.md
  en/upgrade/centreon-ha/upgrade-from-20.10.md
  en/upgrade/upgrade-from-18-10.md
  en/upgrade/upgrade-from-19-04.md
  en/upgrade/upgrade-from-19-10.md
  en/upgrade/upgrade-from-20-04.md
  en/upgrade/upgrade-from-20-10.md
  en/upgrade/upgrade-from-3-4.md
  fr/graph-views/install.md
  fr/graph-views/upgrade.md
  fr/health/centreon-agent.md
  fr/installation/installation-of-a-central-server/using-packages.md
  fr/installation/installation-of-a-poller/using-packages.md
  fr/installation/installation-of-a-remote-server/using-packages.md
  fr/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
  fr/upgrade/centreon-ha/upgrade-from-20.04.md
  fr/upgrade/centreon-ha/upgrade-from-20.10.md
  fr/upgrade/upgrade-from-18-10.md
  fr/upgrade/upgrade-from-19-04.md
  fr/upgrade/upgrade-from-19-10.md
  fr/upgrade/upgrade-from-20-04.md
  fr/upgrade/upgrade-from-20-10.md
  fr/upgrade/upgrade-from-3-4.md
Labels: area/backend

#1190 fix(doc) wrong link to access to blockchain Packs + reorder
  en/integrations/plugin-packs/procedures/blockchain-parity-ethpoller-restapi.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/blockchain-parity-ethpoller-restapi.md
  fr/sidebars.json
Labels: pack-monitoring-proc

#1195 enh(doc) missing monitoring proc december Pack release
  en/assets/integrations/plugin-packs/procedures/cloud-azure-storage-acr-provider.png
  en/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
  en/integrations/plugin-packs/procedures/applications-nmap-cli.md
  en/integrations/plugin-packs/procedures/cloud-azure-storage-acr.md
  en/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md
  en/integrations/plugin-packs/procedures/operatingsystems-as400.md
  en/sidebars.json
  fr/assets/integrations/plugin-packs/procedures/cloud-azure-storage-acr-provider.png
  fr/integrations/plugin-packs/procedures/applications-netbackup-ssh.md
  fr/integrations/plugin-packs/procedures/applications-nmap-cli.md
  fr/integrations/plugin-packs/procedures/cloud-azure-storage-acr.md
  fr/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md
  fr/integrations/plugin-packs/procedures/operatingsystems-as400.md
  fr/sidebars.json
Labels: pack-monitoring-proc

#1209 enh(release): Anomaly 21.04.2 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 21.04

#1206 enh(release): Add Centreon Web 21.04.10 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#1207 enh(release): Add Centreon Web 20.10.15 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#711 enh(release): Add Centreon Anomaly Detection 20.10.1 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.10

#1205 enh(release): Add Centreon Web 21.10.2 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.10

#1210 enh(release): Anomaly 21.10.1 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 21.10

#1214 enh(release): add Centreon Open Ticket 20.10.3 RN
  en/releases/centreon-os-extensions.md
  fr/releases/centreon-os-extensions.md
Labels: 20.10

#1215 enh(release): add Centreon Open Ticket 21.04.2 RN
  en/releases/centreon-os-extensions.md
  fr/releases/centreon-os-extensions.md
Labels: 21.04

#1213 enh(release): add Centreon License Manager 21.04.1 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 21.04
