Repository centreon/centreon-documentation, pull requests merged in 2021-01, with the labels that each got.

#468 enh(release): Add centreon-ha 20.10.1 release notes
  en/releases/centreon-os-extensions.md
  fr/releases/centreon-os-extensions.md
Labels: 20.10

#490 doc(module): improve documentation to dev a module
  en/developer/developer-module.md
  fr/developer/developer-module.md
Labels: area/backend

#469 enh(release): add Centreon Web 20.10.2 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#538 enh(release): Add Centreon web 20.04.8 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#523 add(epp): hitachi hcp snmp proc
  en/integrations/plugin-packs/procedures/hardware-storage-hitachi-hcp-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/hardware-storage-hitachi-hcp-snmp.md
  fr/sidebars.json
Labels: approved-waiting-release, pack-monitoring-proc

#522 new(mp)cloud-azure-management-log-analytics
  en/integrations/plugin-packs/procedures/cloud-azure-management-loganalytics.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/cloud-azure-management-loganalytics.md
  fr/sidebars.json
Labels: approved-waiting-release, pack-monitoring-proc

#496 add(epp): AWS Transit gateway monit proc
  en/integrations/plugin-packs/procedures/cloud-aws-transitgateway.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/cloud-aws-transitgateway.md
  fr/sidebars.json
Labels: approved-waiting-release, pack-monitoring-proc

#517 add(epp): hms ewon snmp monitoring proc
  en/integrations/plugin-packs/procedures/hardware-devices-hms-ewon-snmp.md
  en/sidebars.json
  fr/integrations/plugin-packs/procedures/hardware-devices-hms-ewon-snmp.md
  fr/sidebars.json
Labels: approved-waiting-release, pack-monitoring-proc

#436 enh(multi): monitoring servers addition, group membership, network flows
  en/installation/architectures.md
  en/installation/prerequisites.md
  en/monitoring/monitoring-servers/add-a-poller-to-configuration.md
  en/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md
  fr/installation/architectures.md
  fr/installation/prerequisites.md
  fr/monitoring/monitoring-servers/add-a-poller-to-configuration.md
  fr/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md
Labels: 20.10

#497 enh(mp): application-monitoring-alyvix-restapi
  en/integrations/plugin-packs/procedures/applications-monitoring-alyvix-restapi.md
  fr/integrations/plugin-packs/procedures/applications-monitoring-alyvix-restapi.md
Labels: pack-monitoring-proc

#546 enh(release): add release date for major version
  en/releases/introduction.md
  fr/releases/introduction.md
Labels: 20.10

#550 enh(chore): update security policy GPG key
  SECURITY.md
Labels: area/backend

#527 enh(release): prepare broker 20.10.3 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#528 enh(release): prepare broker 20.04.12 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#529 enh(release): prepare engine 20.10.2 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.10

#530 enh(release): prepare engine 20.04.9 release notes
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 20.04

#451 enh(clapi): document pool_size broker property
  en/api/clapi.md
  fr/api/clapi.md
Labels: web-20.10.2

#557 Update howto translate centreon
  en/developer/developer-translate-centreon.md
  fr/developer/developer-translate-centreon.md
Labels: 20.04, 20.10, enhancement

#526 enh(release): prepare gorgone 20.10.2 release notes
  en/releases/centreon-commercial-extensions.md
  en/releases/centreon-core.md
  en/releases/centreon-os-extensions.md
  fr/releases/centreon-commercial-extensions.md
  fr/releases/centreon-core.md
  fr/releases/centreon-os-extensions.md
Labels: 20.10

#531 enh(release): prepare gorgone 20.04.9 release notes
  en/releases/centreon-commercial-extensions.md
  en/releases/centreon-core.md
  en/releases/centreon-os-extensions.md
  fr/releases/centreon-commercial-extensions.md
  fr/releases/centreon-core.md
  fr/releases/centreon-os-extensions.md
Labels: 20.04

#563 enh(release): change dates to render as tag
  en/releases/centreon-commercial-extensions.md
  en/releases/centreon-core.md
  en/releases/centreon-os-extensions.md
  fr/releases/centreon-commercial-extensions.md
  fr/releases/centreon-core.md
  fr/releases/centreon-os-extensions.md
Labels: 20.10

#564 enh(release): change dates to render as tag
  en/releases/centreon-commercial-extensions.md
  en/releases/centreon-core.md
  en/releases/centreon-os-extensions.md
  fr/releases/centreon-commercial-extensions.md
  fr/releases/centreon-core.md
  fr/releases/centreon-os-extensions.md
Labels: 20.04
