Repository centreon/centreon-documentation, pull requests merged in 2022-08, with the labels that each got.

#1692 Migrate Huawei documentation to the newest layout
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-huawei-snmp.md
  pp/integrations/plugin-packs/procedures/network-huawei-snmp.md
Labels: area/connectors

#1691 Add Office365 Azure AD monproc
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-azuread.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
  pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-azuread.md
  pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
  pp/sidebarsPp.js
Labels: area/connectors

#1693 Fix 404 links in MS Teams monitoring procedure
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-teams.md
  pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-teams.md
Labels: area/connectors

#1647 NEXT PS-62 - Fix constraints on HA 2 nodes
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-04.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
  versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-04.md
  versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
Labels: HA

#1698 add(epp): dell vxrail manager rest api
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-dell-vxm-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-servers-dell-vxm-restapi.md
  pp/sidebarsPp.js
Labels: area/connectors

#1609 enh(release): add security policy information in release note
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
  versioned_docs/version-22.04/releases/centreon-core.md
Labels: area/backend

#1689 Add Alcatel OXE documentation v2 format
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-telephony-alcatel-oxe-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-telephony-alcatel-oxe-snmp.md
Labels: area/connectors

#1646 PS-62 - Fix constraints on HA 2 nodes
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/centreon-ha/upgrade-from-21-04.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/centreon-ha/upgrade-from-21-10.md
  versioned_docs/version-22.04/upgrade/centreon-ha/upgrade-from-21-04.md
  versioned_docs/version-22.04/upgrade/centreon-ha/upgrade-from-21-10.md
Labels: HA

#1706 enh(doc): add snmpv3 mapping option
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
  pp/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
Labels: area/connectors

#1707 add(epp): adding Windows node exporter documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-windows.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-windows.md
  pp/sidebarsPp.js
Labels: area/connectors

#1556 (fix) ha upgrade process for old versions
  i18n/fr/docusaurus-plugin-content-docs/version-21.04/upgrade/centreon-ha/upgrade-from-20.04.md
  i18n/fr/docusaurus-plugin-content-docs/version-21.04/upgrade/centreon-ha/upgrade-from-20.10.md
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/centreon-ha/upgrade-from-20-04.md
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/centreon-ha/upgrade-from-20-10.md
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/centreon-ha/upgrade-from-21-04.md
  versioned_docs/version-21.04/upgrade/centreon-ha/upgrade-from-20.04.md
  versioned_docs/version-21.04/upgrade/centreon-ha/upgrade-from-20.10.md
  versioned_docs/version-21.10/upgrade/centreon-ha/upgrade-from-20-04.md
  versioned_docs/version-21.10/upgrade/centreon-ha/upgrade-from-20-10.md
  versioned_docs/version-21.10/upgrade/centreon-ha/upgrade-from-21-04.md
Labels: HA

#1722 fix(pp) - Fixing outdated command option in Kadiska PP documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md
Labels: area/connectors

#1720 enh(pp) - migrate Azure recovery to v2 format
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-azure-management-recovery-provider.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-recovery.md
  pp/assets/integrations/plugin-packs/procedures/cloud-azure-management-recovery-provider.png
  pp/integrations/plugin-packs/procedures/cloud-azure-management-recovery.md
Labels: enhancement, area/connectors

#1727 add(epp): netgear sseries snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-netgear-sseries-snmp.md
  pp/integrations/plugin-packs/procedures/network-netgear-sseries-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#1740 enh(epp): dell powerstore rest api - update doc
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-dell-powerstore-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-storage-dell-powerstore-restapi.md
Labels: area/connectors

#1742 enh(epp): aruba aoscx snmp - update doc
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
  pp/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
Labels: area/connectors

#1739 PS-88 Update-centreon-HA-monitoring for resource php
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-ha.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-ha.md
Labels: area/connectors

#1744 add(epp): hp moonshot snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-moonshot-snmp.md
  pp/integrations/plugin-packs/procedures/network-hp-moonshot-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#1761 add(epp): fortinet fortigate rest api
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortigate-restapi.md
  pp/integrations/plugin-packs/procedures/network-fortinet-fortigate-restapi.md
  pp/sidebarsPp.js
Labels: area/connectors

#1760 fix(pp) - Removing deprecated stpl mention in documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-virtualmachine.md
  pp/integrations/plugin-packs/procedures/cloud-azure-compute-virtualmachine.md
Labels: area/connectors

#1741 add(pp) - Adding documentation for Cisco Umbrella Plugin pack
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#1763 enh(pp) Azure Recovery - Adding replication-health service template
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-recovery.md
  pp/integrations/plugin-packs/procedures/cloud-azure-management-recovery.md
Labels: area/connectors

#1648 fix(clapi): update clapi documentation for contact template
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/clapi.md
  versioned_docs/version-22.04/api/clapi.md
Labels: area/backend
