Repository centreon/centreon-documentation, pull requests merged in 2022-09, with the labels that each got.

#1781 enh(epp): one access snmp - add rtt-probes mode
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-oneaccess-snmp.md
  pp/integrations/plugin-packs/procedures/network-oneaccess-snmp.md
Labels: area/connectors

#1777 enh(epp): hp 3par proc v2
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hp-3par-ssh.md
  pp/integrations/plugin-packs/procedures/hardware-storage-hp-3par-ssh.md
  pp/sidebarsPp.js
Labels: area/connectors

#1774 add(epp): iics rest api
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-iics-restapi.md
  pp/integrations/plugin-packs/procedures/cloud-iics-restapi.md
  pp/sidebarsPp.js
Labels: area/connectors

#1711 Adding AWS Unified Discovery and modifying AWS VPN documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover-accessparameters.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover-credentials.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover-discoparameters.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover-provider.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover-results.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-aws-vpn-provider.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-vpn.md
  pp/assets/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover-accessparameters.png
  pp/assets/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover-credentials.png
  pp/assets/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover-discoparameters.png
  pp/assets/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover-provider.png
  pp/assets/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover-results.png
  pp/assets/integrations/plugin-packs/procedures/cloud-aws-vpn-provider.png
  pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatch-discover
  pp/integrations/plugin-packs/procedures/cloud-aws-vpn.md
Labels: area/connectors

#1794 enh(epp): emc vplex rest api proc v2
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-emc-vplex-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-storage-emc-vplex-restapi.md
Labels: area/connectors

#1796 Enh(doc) add discovery rule for windows NRPE + translation FR
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
  pp/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
Labels: area/connectors

#1800 Fix PagerDuty spelling
  versioned_docs/version-22.04/integrations/event-management/sc-pagerduty-events.md
Labels: area/connectors

#1640 PS-56 - Add manage disabled resources.
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha/installation-2-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha/installation-4-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha/installation-2-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha/installation-4-nodes.md
  versioned_docs/version-21.10/installation/installation-of-centreon-ha/installation-2-nodes.md
  versioned_docs/version-21.10/installation/installation-of-centreon-ha/installation-4-nodes.md
  versioned_docs/version-22.04/installation/installation-of-centreon-ha/installation-2-nodes.md
  versioned_docs/version-22.04/installation/installation-of-centreon-ha/installation-4-nodes.md
Labels: HA

#1769 enh(core): update libs and optimize build with swc (next)
  Jenkinsfile
  docusaurus.config.js
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/connect/loginpwd.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/getting-started/interface.md
  package.json
  src/css/custom.css
  versioned_docs/version-22.10/connect/loginpwd.md
  versioned_docs/version-22.10/getting-started/interface.md
  yarn.lock
Labels: area/ui

#1773 enh(core): update libs and optimize build with swc (staging)
  Jenkinsfile
  docusaurus.config.js
  package.json
  src/css/custom.css
  versioned_docs/version-21.10/administration/secure-platform.md
  yarn.lock
Labels: area/ui

#1808 Add Azure Costs monitoring proc
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-costs.md
  pp/integrations/plugin-packs/procedures/cloud-azure-management-costs.md
  pp/sidebarsPp.js
Labels: area/connectors

#1785 Enhance Oracle prerequisites section
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-oracle.md
  pp/integrations/plugin-packs/procedures/applications-databases-oracle.md
Labels: area/connectors

#1810 Fix tab alignment in monitoring pack release note
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#1643 Ps 34 manual ha installation Next
  i18n/fr/docusaurus-plugin-content-docs/version-22.10.json
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/installation-2-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha-manual/integrating-pollers.md
  versioned_docs/version-22.10/installation/installation-of-centreon-ha-manual/installation-2-nodes.md
  versioned_docs/version-22.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
  versioned_docs/version-22.10/installation/installation-of-centreon-ha-manual/integrating-pollers.md
  versioned_sidebars/version-22.10-sidebars.json
Labels: HA

#1585 PS-34 - Add doc for centreon-HA Manual in 21.10
  i18n/fr/docusaurus-plugin-content-docs/version-21.10.json
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha-manual/installation-2-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha-manual/integrating-pollers.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.04.json
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha-manual/installation-2-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha-manual/integrating-pollers.md
  versioned_docs/version-21.10/installation/installation-of-centreon-ha-manual/installation-2-nodes.md
  versioned_docs/version-21.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
  versioned_docs/version-21.10/installation/installation-of-centreon-ha-manual/integrating-pollers.md
  versioned_docs/version-22.04/installation/installation-of-centreon-ha-manual/installation-2-nodes.md
  versioned_docs/version-22.04/installation/installation-of-centreon-ha-manual/installation-4-nodes.md
  versioned_docs/version-22.04/installation/installation-of-centreon-ha-manual/integrating-pollers.md
  versioned_sidebars/version-21.10-sidebars.json
  versioned_sidebars/version-22.04-sidebars.json
Labels: HA

#1818 doc(release): add release note for centreon-collect-21.10.3
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
  versioned_docs/version-21.10/releases/centreon-core.md
Labels: 21.10
