Repository centreon/centreon-documentation, pull requests merged in 2022-02, with the labels that each got.

#1290 enh(release): Add Centreon PPM 20.04.3 RN
  en/releases/centreon-commercial-extensions.md
  fr/releases/centreon-commercial-extensions.md
Labels: 20.04

#1292 enh(release): Add Centreon Web 21.04.11 RN
  en/releases/centreon-core.md
  fr/releases/centreon-core.md
Labels: 21.04

#1318 add samesite parameter to set cookie (next)
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md
  versioned_docs/version-22.04/administration/secure-platform.md
Labels: area/backend

#1317 add samesite parameter to set cookie
  i18n/fr/docusaurus-plugin-content-docs/version-20.04/administration/secure-platform.md
  i18n/fr/docusaurus-plugin-content-docs/version-20.10/administration/secure-platform.md
  i18n/fr/docusaurus-plugin-content-docs/version-21.04/administration/secure-platform.md
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/administration/secure-platform.md
  versioned_docs/version-20.04/administration/secure-platform.md
  versioned_docs/version-20.10/administration/secure-platform.md
  versioned_docs/version-21.04/administration/secure-platform.md
  versioned_docs/version-21.10/administration/secure-platform.md
Labels: area/backend
