Repository centreon/centreon-documentation, pull requests merged in 2022-07, with the labels that each got.

#1645 enh(doc): added MBI 22.04.1 release notes
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
  versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
Labels: documentation, area/backend

#1649 fix(clapi): update clapi documentation for contact template (next)
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/clapi.md
  versioned_docs/version-22.10/api/clapi.md
Labels: area/backend

#1661 enh(epp): postgresql proc v2
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
  pp/integrations/plugin-packs/procedures/applications-databases-postgresql.md
Labels: area/connectors

#1668 add(pp) - Adding PP documentation for Azure Classic Storage
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-classic-storage-storageaccount.md
  pp/integrations/plugin-packs/procedures/cloud-azure-classic-storage-storageaccount.md
  pp/sidebarsPp.js
Labels: area/connectors

#1669 enh(pp) - adding missing metrics and provider icon
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-azure-classic-storage-storageaccount-provider.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-classic-storage-storageaccount.md
  pp/assets/integrations/plugin-packs/procedures/cloud-azure-classic-storage-storageaccount-provider.png
  pp/integrations/plugin-packs/procedures/cloud-azure-classic-storage-storageaccount.md
Labels: area/connectors

#1670 enh(epp) - docv2 format for Azure Storage Account PP
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-azure-storage-storageaccount-provider.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-storage-storageaccount.md
  pp/assets/integrations/plugin-packs/procedures/cloud-azure-storage-storageaccount-provider.png
  pp/integrations/plugin-packs/procedures/cloud-azure-storage-storageaccount.md
Labels: area/connectors

#1673 Fix name issue with Azure Storages MP
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-classicstorage-storageaccount.md
  pp/integrations/plugin-packs/procedures/cloud-azure-classicstorage-storageaccount.md
  pp/sidebarsPp.js
Labels: area/connectors

#1627 update(doc) hardware.storage.fujitsu.eternus.dx.ssh
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-fujitsu-eternus-dx-ssh.md
  pp/integrations/plugin-packs/procedures/hardware-storage-fujitsu-eternus-dx-ssh.md
Labels: area/connectors

#1517 fix(doc) update template
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ats-apc.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-clever-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-emerson-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-akcp-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-hwgste-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-sensorip-snmp.md
  pp/integrations/plugin-packs/procedures/applications-protocol-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-ats-apc.md
  pp/integrations/plugin-packs/procedures/hardware-pdu-clever-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-pdu-emerson-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-akcp-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-hwgste-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-sensorip-snmp.md
Labels: area/connectors

#1636 update(doc) Network CISCO WLC SNMP
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
Labels: area/connectors

#1663 update(doc) Alcatel Omniswitch SNMP
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
Labels: area/connectors

#1680 enh(epp) - Prometheus server and targets in v2 format
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-prometheus-api-provider.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-prometheus-api.md
  pp/assets/integrations/plugin-packs/procedures/cloud-prometheus-api-provider.png
  pp/integrations/plugin-packs/procedures/cloud-prometheus-api.md
Labels: area/connectors

#1677 Fix uncatched typos introduced in recent PR
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-vmscalesets.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ats-apc.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-akcp-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-hwgste-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-sensorip-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-brocade-snmp.md
  pp/integrations/plugin-packs/procedures/applications-protocol-snmp.md
  pp/integrations/plugin-packs/procedures/cloud-azure-compute-vmscalesets.md
  pp/integrations/plugin-packs/procedures/hardware-ats-apc.md
  pp/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-akcp-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-hwgste-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-sensorip-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-brocade-snmp.md
Labels: area/connectors

#1553 update(doc) protocol http
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-http.md
  pp/integrations/plugin-packs/procedures/applications-protocol-http.md
Labels: area/connectors
