Repository centreon/centreon-documentation, pull requests merged in 2023-03, with the labels that each got.

#2142 enh(epp): hardware-ups-standard-rfc1628-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-standard-rfc1628-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-ups-standard-rfc1628-snmp.md
Labels: area/connectors

#2139 add(epp): hardware-ups-riello-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-riello-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-ups-riello-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#2171 ad(epp): applications-controlm-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-controlm-restapi.md
  pp/integrations/plugin-packs/procedures/applications-controlm-restapi.md
  pp/sidebarsPp.js
Labels: area/connectors

#2141 enh(epp): hardware-pdu-raritan-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
Labels: area/connectors

#2153 Add Cisco WLC documentation after updating Plugin-pack
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
Labels: area/connectors

#2149 MON-15626-add-azure-management-policies-pack
  .gitignore
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
  pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
  pp/sidebarsPp.js
Labels: area/connectors

#2173 MON-16159-plugin-pack-centreon-pack-virtualization-vmware-2-esx-host-…
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
  pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
Labels: documentation

#2186 doc(release): release notes for Connectors 23.03
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#2126 MON-15484-add-missing-packs-from-azure-discover
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
  pp/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
Labels: documentation, area/connectors

#2162 Enhance HTTPS documentation
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/administration/secure-platform.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md
  versioned_docs/version-21.10/administration/secure-platform.md
  versioned_docs/version-22.04/administration/secure-platform.md
  versioned_docs/version-22.10/administration/secure-platform.md
Labels: documentation, enhancement

#2207 fix typos
  pp/integrations/plugin-packs/procedures/applications-antivirus-kaspersky-snmp.md
  pp/integrations/plugin-packs/procedures/applications-databases-elasticsearch.md
  pp/integrations/plugin-packs/procedures/network-ibm-bladecenter-snmp.md
  pp/integrations/plugin-packs/procedures/network-lenovo-flexsystem-snmp.md
Labels: area/connectors
