Repository centreon/centreon-documentation, pull requests merged in 2023-01, with the labels that each got.

#2057 Push MON-15001 to next branch
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
  versioned_docs/version-23.04/reporting/installation.md
Labels: MBI

#2058 Change php path to next branch MON-15940
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
  versioned_docs/version-23.04/reporting/installation.md
Labels: documentation, MBI

#2059 Push install MBI 22.04&22.10 MON-15940
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
  versioned_docs/version-22.04/reporting/installation.md
  versioned_docs/version-22.10/reporting/installation.md
Labels: documentation, MBI

#2078 add(epp): cloud talend tmc api
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-talend-tmc-api.md
  pp/integrations/plugin-packs/procedures/cloud-talend-tmc-api.md
  pp/sidebarsPp.js
Labels: area/connectors

#2055 enh(epp): refactoring purestorage
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-api.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-flasharray-legacy-restapi.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-flasharray-v2-restapi.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-flashblade-v2-restapi.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-storage-purestorage-api.md
  pp/integrations/plugin-packs/procedures/hardware-storage-purestorage-flasharray-legacy-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-storage-purestorage-flasharray-v2-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-storage-purestorage-flashblade-v2-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-storage-purestorage-restapi.md
  pp/sidebarsPp.js
Labels: area/connectors

#2043 MON-14033-add-host-discovery-rules-to-aws-cloudfront-pack
  i18n/fr/docusaurus-plugin-content-docs-pp/current/assets/integrations/plugin-packs/procedures/cloud-aws-cloudfront-provider.png
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
  pp/assets/integrations/plugin-packs/procedures/cloud-aws-cloudfront-provider.png
  pp/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
Labels: area/connectors
