Repository centreon/centreon-documentation, pull requests merged in 2023-04, with the labels that each got.

#2152 Ps 112 upgrading ha rhel8 21.10 to 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
  versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
Labels: HA

#1984 Ps 117 centreon ha 4nodes updates
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha/installation-2-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha/installation-4-nodes.md
  versioned_docs/version-22.10/installation/installation-of-centreon-ha/installation-2-nodes.md
  versioned_docs/version-22.10/installation/installation-of-centreon-ha/installation-4-nodes.md
Labels: HA

#2129 PS-112 Upgrade 22.10 RHEL8 HA 2nodes 21.04 to 22.10 - update commands and outputs
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-04.md
  versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-04.md
Labels: HA

#2217 add(epp): network-opengear-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-opengear-snmp.md
  pp/integrations/plugin-packs/procedures/network-opengear-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#2206 add(epp): network-aruba-cppm-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
  pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#2178 MON-14220-allow-user-to-use-ip-management-attribute-in-mapper-definit…
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
  pp/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
Labels: documentation, area/connectors
