Repository centreon/centreon-documentation, pull requests merged in 2023-10, with the labels that each got.

#2658 doc(release): Prepare release notes for modules 22.04
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
  versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
Labels: release-notes

#2661 doc(release): Prepare release notes for modules 21.10
  i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
  versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
Labels: release-notes

#2634 doc(release): Prepare release notes for modules 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
  versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Labels: release-notes

#2682 doc(release): Prepare release notes for oss 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#2680 doc(release): Prepare release notes for oss 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#2695 doc(release): Prepare release notes for modules 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#2611 add(epp): applications-databases-mongodb
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mongodb.md
  pp/integrations/plugin-packs/procedures/applications-databases-mongodb.md
Labels: area/connectors

#2466 add(epp): hardware-ups-ees-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-ups-ees-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#2703 Update applications-databases-postgresql
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
  pp/integrations/plugin-packs/procedures/applications-databases-postgresql.md
Labels: area/connectors

#2708 Updating cAdvisor procedure
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
  pp/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
Labels: area/connectors

#2726 Update EC2 MC procedure
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ec2.md
  pp/integrations/plugin-packs/procedures/cloud-aws-ec2.md
Labels: area/connectors

#2686 enh(mc): Refreshed Azure Functions page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
  pp/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
Labels: area/connectors

#2712 [MON-21088] - [Documentation] Enhance database mysql plugin sql string
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mssql.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mysql.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-oracle.md
  pp/integrations/plugin-packs/procedures/applications-databases-mssql.md
  pp/integrations/plugin-packs/procedures/applications-databases-mysql.md
  pp/integrations/plugin-packs/procedures/applications-databases-oracle.md
  pp/sidebarsPp.js
Labels: area/connectors

#2732 Update Fortigate RestAPI procedure
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortigate-restapi.md
  pp/integrations/plugin-packs/procedures/network-fortinet-fortigate-restapi.md
Labels: area/connectors

#2727 Update AWS RDS procedure
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-rds.md
  pp/integrations/plugin-packs/procedures/cloud-aws-rds.md
Labels: area/connectors

#2745 Poller installation command
  cloud/installation/deploy-poller.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md
Labels: cloud
