Repository centreon/centreon-documentation, pull requests merged in 2023-07, with the labels that each got.

#2405 enh(epp): network-oneaccess-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-oneaccess-snmp.md
  pp/integrations/plugin-packs/procedures/network-oneaccess-snmp.md
Labels: area/connectors

#2421 add(epp): network-fortinet-fortimail-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortimail-snmp.md
  pp/integrations/plugin-packs/procedures/network-fortinet-fortimail-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#2414 enh(epp): network-cisco-wlc-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
Labels: area/connectors

#2378 enh(epp): applications-rubrik-restapi - update proc
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
  pp/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
Labels: area/connectors

#2371 add(epp): applications-veeam-vbem-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
  pp/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
  pp/sidebarsPp.js
Labels: area/connectors

#2365 enh(pack): refreshed the pack's page - Ansible Tower CLI
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ansible-tower.md
  pp/integrations/plugin-packs/procedures/applications-ansible-tower.md
  pp/sidebarsPp.js
Labels: area/connectors

#2389 enh(epp): applications-ipfabric-api
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ipfabric-api.md
  pp/integrations/plugin-packs/procedures/applications-ipfabric-api.md
  pp/sidebarsPp.js
Labels: area/connectors

#2415 enh(epp): paloalto standard snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-snmp.md
Labels: area/connectors

#2432 MON-19264 - Documentation - Depreciate the ip label datametrie monitoring connector
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-iplabel-datametrie-restapi.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-iplabel-datametrie-restapi.md
Labels: area/connectors

#2240 MON-16300-plugin-pack-centreon-pack-hardware-servers-xfusion-ibmc-snm…
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-xfusion-ibmc-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-servers-xfusion-ibmc-snmp.md
Labels: documentation

#2502 doc(release): prepare release notes for collect 23.04.2
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#2503 doc(release): prepare release notes for collect 22.10.4
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#2505 doc(release): prepare release notes for oss 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#2509 doc(release): prepare release notes for oss 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#2510 doc(release): prepare release notes for oss 22.04
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-os-extensions.md
  versioned_docs/version-22.04/releases/centreon-core.md
  versioned_docs/version-22.04/releases/centreon-os-extensions.md
Labels: release-notes

#2512 doc(release): prepare release notes for modules 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
  versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Labels: release-notes

#2511 doc(release): prepare release notes for modules 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes
