Repository centreon/centreon-documentation, pull requests merged in 2024-01, with the labels that each got.

#2936 ench(chore): code owners feedbacks
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/actionlint.yml
Labels: gha

#2939 enh(ci): upgrade gh actions
  .github/workflows/archive.yml
  .github/workflows/dependabot_jira.yml
  .github/workflows/documentation.yml
Labels: gha

#2941 doc(release): prepare release notes for OSS 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#2938 doc(Release): Prepare release notes for OSS 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#2943 doc(release): Prepare release notes for oss 22.04
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
  versioned_docs/version-22.04/releases/centreon-core.md
Labels: release-notes

#2942 doc(release): Prepare release notes for oss 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#2946 doc(release): Prepare release notes for OSS 23.04
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#2954 doc(release): prepare release notes for collect 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#2956 doc(release): Prepare release notes for collect 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#2955 doc(release): Prepare release notes for collect 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#2959 doc(release): Prepare release notes for OSS 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#2961 doc(release): prepare release notes for OSS 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#2966 doc(release): Prepare release notes for OSS 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#2965 doc(release): Prepare release notes for oss 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#2952 enh(mc): refresh warp10 procedure
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-warp10-sensision.md
  pp/integrations/plugin-packs/procedures/applications-databases-warp10-sensision.md
Labels: area/connectors

#2960 add(mc): new Avocent 8000 monitoring connector
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-kvm-avocent-acs-8000-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-kvm-avocent-acs-8000-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#2953 [CTOR-46] [Documentation] Add Pack Teldat SNMP
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-teldat-snmp.md
  pp/integrations/plugin-packs/procedures/network-teldat-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#2963 enh(mc): updating Dell XSeries
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-dell-xseries-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-dell-xseries-snmp.md
Labels: area/connectors

#2968 enh(rn): MCR 24.01 release notes
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#2967 doc(release): Prepare release notes for Modules 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#2981 doc(release): prepare release notes for modules 22.04
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
  versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
Labels: release-notes

#2986 doc(release): Prepare release notes for modules 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#2871 enh(mc): Great Reboot - network-firewalls-fortinet-fortigate-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-fortinet-fortigate-snmp.md
  pp/integrations/plugin-packs/procedures/network-firewalls-fortinet-fortigate-snmp.md
Labels: area/connectors

#2918 Refresh the network aruba instant snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
  pp/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
Labels: area/connectors

#2873 enh(mc): Great Reboot - network-switchs-hp-procurve-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-hp-procurve-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-hp-procurve-snmp.md
Labels: area/connectors

#2935 Refresh the network-switchs-mrv-optiswitch-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-mrv-optiswitch-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-mrv-optiswitch-snmp.md
Labels: area/connectors

#2928 Refresh the network-extreme-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-extreme-snmp.md
  pp/integrations/plugin-packs/procedures/network-extreme-snmp.md
Labels: area/connectors

#2987 doc(release): prepare release notes for OSS 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#2874 enh(mc): Great Reboot - network-hp-standard-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-hp-standard-snmp.md
Labels: area/connectors

#2872 Refresh the vmware vcenter generic doc
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
  pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
Labels: area/connectors

#2997 doc(release): prepare release notes for Modules 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#2920 Refresh the network-switchs-brocade-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-brocade-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-brocade-snmp.md
Labels: area/connectors

#2875 enh(mc): Great Reboot - network-switchs-aruba-standard-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-aruba-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-aruba-standard-snmp.md
Labels: area/connectors

#2919 refresh the network-firewalls-pfsense-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-pfsense-snmp.md
  pp/integrations/plugin-packs/procedures/network-firewalls-pfsense-snmp.md
Labels: area/connectors

#2921 Refresh the network-stormshield-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-stormshield-snmp.md
  pp/integrations/plugin-packs/procedures/network-stormshield-snmp.md
Labels: area/connectors

#2922 refresh the network-fortinet-fortimanager-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortimanager-snmp.md
  pp/integrations/plugin-packs/procedures/network-fortinet-fortimanager-snmp.md
Labels: area/connectors
