Repository centreon/centreon-documentation, pull requests merged in 2024-10, with the labels that each got.

#3633 doc(release) Release notes for map 24.04.5 / mbi 24.04.3 / ppm 24.04.1
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3533 CTOR-752 : Former mandatory option in applications-rubrik-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
  pp/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
Labels: area/connectors

#3635 CTOR-864 : Refresh Network-cisco-Meraki
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-meraki-restapi.md
  pp/integrations/plugin-packs/procedures/network-cisco-meraki-restapi.md
Labels: area/connectors

#3636 fix(mbi): edit command for MBI : Access to the Central database
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/reporting/installation.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/reporting/installation.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/reporting/installation.md
  versioned_docs/version-22.10/reporting/installation.md
  versioned_docs/version-23.04/reporting/installation.md
  versioned_docs/version-23.10/reporting/installation.md
  versioned_docs/version-24.04/reporting/installation.md
  versioned_docs/version-24.10/reporting/installation.md
Labels: area/backend

#3628 CTOR-950 : Pack(Applications-rapidrecovery-snmp) : Fix commands typo for both modes
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rapidrecovery-snmp.md
  pp/integrations/plugin-packs/procedures/applications-rapidrecovery-snmp.md
Labels: area/connectors

#3614 CTOR-887 : Plugin(hardware::pdu::cyberpower::snmp) - Mode(load) : StatusPower should not be multiplied by 10
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md
Labels: area/connectors

#3638 CTOR-542 : Plugin(os::linux::snmp) - Mode(memory) : Issue in case very big memory size
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmpv3.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmpv3.md
Labels: area/connectors

#3618 CTOR-397 : [Plugin(storage::wd::nas::snmp) - Modes(volumes, listvolumes, hardware) : add support for ex4100 model
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
Labels: area/connectors

#3606 [Cloud] Time periods in notifications
  cloud/alerts-notifications/notif-configuration.md
  cloud/monitoring/basic-objects/timeperiods.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/notif-configuration.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/timeperiods.md
Labels: cloud

#3599 Update Known Issues for Cloud 24.09
  cloud/resources/known-issues.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/known-issues.md
Labels: cloud

#3564 Update list of widgets for Cloud 24.09 (clock/timer)
  cloud/alerts-notifications/dashboards.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Labels: cloud

#3641 feat(mc-cma-linux): new monitoring connector - Linux with Centreon Monitoring Agent
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-centreon-monitoring-agent.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-centreon-monitoring-agent.md
  pp/sidebarsPp.js
Labels: area/connectors

#3620 CTOR - 815 : add(network::cisco::standard::snmp): add option --add-fc-fe-errors
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
Labels: area/connectors

#3632 chore(deps): absorb 24.10 dependabot GitHub Actions updates
  .github/workflows/actionlint.yml
  .github/workflows/archive.yml
  .github/workflows/documentation.yml
Labels: dependencies, gha

#3657 Ctor-876 : Connectors 24.10 release
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ansible-tower.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rapidrecovery-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-centreon-monitoring-agent.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmpv3.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/procedures/applications-ansible-tower.md
  pp/integrations/plugin-packs/procedures/applications-rapidrecovery-snmp.md
  pp/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-standard-snmp.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-centreon-monitoring-agent.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmpv3.md
  pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
  pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
  pp/integrations/plugin-packs/releases/release-notes.md
  pp/sidebarsPp.js
Labels: area/connectors

#3660 Fix on connectors release note : Replace fix sectiond with bug fixes
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#3664 fast-update-on-windows-linux-cma-connectors
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-centreon-monitoring-agent.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-centreon-monitoring-agent.md
  pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
Labels: area/connectors

#3560 CTOR-895 : Refresh network-cisco-esa-xmlapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-esa-xmlapi.md
  pp/integrations/plugin-packs/procedures/network-cisco-esa-xmlapi.md
Labels: area/connectors

#3563 CTOR-898 : Refresh network-cisco-prime-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-prime-restapi.md
  pp/integrations/plugin-packs/procedures/network-cisco-prime-restapi.md
Labels: area/connectors

#3567 [CTOR-834] - Refresh hardware-storage-quantum-scalar-snmp doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-quantum-scalar-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-quantum-scalar-snmp.md
Labels: area/connectors

#3570 [MON-148118] - Refresh Cisco WLC doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
Labels: area/connectors

#3561 CTOR-896 : Refresh network-cisco-firepower-fmc-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
  pp/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md
Labels: area/connectors

#3562 CTOR-897 : Refresh network-cisco-firepower-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md
Labels: area/connectors

#3596 CTOR-919 : Refresh network-alvarion-breezeaccess-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-alvarion-breezeaccess-snmp.md
  pp/integrations/plugin-packs/procedures/network-alvarion-breezeaccess-snmp.md
Labels: area/connectors

#3647 Refresh network-beeware-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-beeware-snmp.md
  pp/integrations/plugin-packs/procedures/network-beeware-snmp.md
Labels: area/connectors

#3572 [CTOR-886]- refresh SAP HANA doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-sap-hana.md
  pp/integrations/plugin-packs/procedures/applications-databases-sap-hana.md
Labels: area/connectors

#3530 CTOR-833 : Refresh hardware-storage-purestorage-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-purestorage-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#3559 CTOR-835 : Refresh hardware-storage-wd-nas-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
Labels: area/connectors

#3577 [CTOR-891] - Refresh Cisco APIC doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-apic-restapi.md
  pp/integrations/plugin-packs/procedures/network-cisco-apic-restapi.md
Labels: area/connectors

#3584 [CTOR-892] - Refresh Cisco Call Manager SNMP doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-callmanager-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-callmanager-snmp.md
Labels: area/connectors

#3576 CTOR-901 : Refresh network-cisco-vcs-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-vcs-restapi.md
  pp/integrations/plugin-packs/procedures/network-cisco-vcs-restapi.md
Labels: area/connectors

#3589 CTOR-915 : Refresh network-acmepacket-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
  pp/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
Labels: area/connectors

#3592 CTOR-916 : Refresh network-adva-fsp150-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-adva-fsp150-snmp.md
  pp/integrations/plugin-packs/procedures/network-adva-fsp150-snmp.md
Labels: area/connectors

#3594 CTOR-917 : Refresh network-aerohive-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aerohive-snmp.md
  pp/integrations/plugin-packs/procedures/network-aerohive-snmp.md
Labels: area/connectors

#3598 CTOR-920 : Refresh network-switchs-arista-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
Labels: area/connectors

#3595 CTOR-918 : Refresh network-allied-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-allied-snmp.md
  pp/integrations/plugin-packs/procedures/network-allied-snmp.md
Labels: area/connectors

#3682 Warn user about language used in public playlist
  cloud/alerts-notifications/dashboards.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Labels: cloud

#3704 doc(release) Release notes map 24.04.6
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3711 doc(release) release notes map 23.10.14
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3575 CTOR-900 : Refresh network-cisco-umbrella-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
Labels: area/connectors

#3579 [CTOR-893] - Refresh the cisco-callmanager-sxml doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
  pp/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
Labels: area/connectors

#3574 CTOR-899 : Refresh network-cisco-standard-ssh
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-standard-ssh.md
  pp/integrations/plugin-packs/procedures/network-cisco-standard-ssh.md
Labels: area/connectors

#3623 CTOR-922 : Refresh network-aruba-orchestrator-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-orchestrator-restapi.md
  pp/integrations/plugin-packs/procedures/network-aruba-orchestrator-restapi.md
Labels: area/connectors

#3602 CTOR-923 : Refresh network-athonet-epc-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-athonet-epc-snmp.md
  pp/integrations/plugin-packs/procedures/network-athonet-epc-snmp.md
Labels: area/connectors

#3642 Refresh network-atto-fibrebridge-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-atto-fibrebridge-snmp.md
  pp/integrations/plugin-packs/procedures/network-atto-fibrebridge-snmp.md
Labels: area/connectors

#3643 Refresh network-barracuda-cloudgen-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-barracuda-cloudgen-snmp.md
  pp/integrations/plugin-packs/procedures/network-barracuda-cloudgen-snmp.md
Labels: area/connectors

#3644 Refresh network-barracuda-bma-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-barracuda-bma-snmp.md
  pp/integrations/plugin-packs/procedures/network-barracuda-bma-snmp.md
Labels: area/connectors

#3649 Refresh network-generic-bluecoat-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-generic-bluecoat-snmp.md
  pp/integrations/plugin-packs/procedures/network-generic-bluecoat-snmp.md
Labels: area/connectors

#3651 Refresh network-citrix-sdx-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-citrix-sdx-snmp.md
  pp/integrations/plugin-packs/procedures/network-citrix-sdx-snmp.md
Labels: area/connectors

#3652 Refresh network-colubris-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-colubris-snmp.md
  pp/integrations/plugin-packs/procedures/network-colubris-snmp.md
Labels: area/connectors

#3653 Refresh virtualization-hpe-simplivity-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-hpe-simplivity-restapi.md
  pp/integrations/plugin-packs/procedures/virtualization-hpe-simplivity-restapi.md
Labels: area/connectors

#3721 doc(release) Release notes for OSS and Collect 24.10.0
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx
  versioned_docs/version-24.10/releases/centreon-os.mdx
Labels: release-notes

#3720 doc(release) Release notes 24.10.0 Modules
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes
