Repository centreon/centreon-documentation, pull requests merged in 2024-03, with the labels that each got.

#3015 Feat(doc) update doc update centreon ha.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-ha.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-ha.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-ha.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-ha.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-ha.md
  versioned_docs/version-22.04/update/update-centreon-ha.md
  versioned_docs/version-22.10/update/update-centreon-ha.md
  versioned_docs/version-23.04/update/update-centreon-ha.md
  versioned_docs/version-23.10/update/update-centreon-ha.md
  versioned_docs/version-24.04/update/update-centreon-ha.md
Labels: documentation, enhancement, HA

#2932 refresh the network-firewalls-checkpoint-snmp doc
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-checkpoint-snmp.md
  pp/integrations/plugin-packs/procedures/network-firewalls-checkpoint-snmp.md
Labels: area/connectors

#2927 Refresh the network-zyxel-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-zyxel-snmp.md
  pp/integrations/plugin-packs/procedures/network-zyxel-snmp.md
Labels: area/connectors

#3098 Fix broken code block
  versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md
Labels: HA

#2949 Refresh the centreon-sql-metrics documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md
Labels: area/connectors

#2948 enh: update applications-monitoring-poller
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md
Labels: area/connectors

#2859 Refresh the vmware vcsa restapi doc
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
  pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-restapi.md
Labels: area/connectors

#2930 Refresh the network-ucopia-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ucopia-snmp.md
  pp/integrations/plugin-packs/procedures/network-ucopia-snmp.md
Labels: area/connectors

#3104 doc(release): prepare release notes for Collect 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#3103 doc(release): Prepare release notes for collect 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3106 Fix(doc) update doc update centreon ha.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-ha.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-ha.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-ha.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-ha.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-ha.md
  versioned_docs/version-22.04/update/update-centreon-ha.md
  versioned_docs/version-22.10/update/update-centreon-ha.md
  versioned_docs/version-23.04/update/update-centreon-ha.md
  versioned_docs/version-23.10/update/update-centreon-ha.md
  versioned_docs/version-24.04/update/update-centreon-ha.md
Labels: documentation, HA

#3108 Add Linux nrpe4
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe4.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe4.md
  pp/sidebarsPp.js
Labels: area/connectors

#3107 feat(monitoring-connector) add documentation for Datacore new plugin …
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
  pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
  pp/sidebarsPp.js
Labels: area/connectors

#3111 enh(rn): release notes for MCR 24.03
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#3115 MCR 24.03
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-bluemind-ssh.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-apc-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-socomec-netvision-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe4.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/procedures/applications-bluemind-ssh.md
  pp/integrations/plugin-packs/procedures/hardware-sensors-apc-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
  pp/integrations/plugin-packs/procedures/hardware-ups-socomec-netvision-snmp.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe4.md
  pp/integrations/plugin-packs/releases/release-notes.md
  pp/sidebarsPp.js
Labels: area/connectors

#2860 Refresh the vmware2 vm doc
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
  pp/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
Labels: area/connectors

#3128 enh(mc): automatic commit for network-watchguard-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-watchguard-snmp.md
  pp/integrations/plugin-packs/procedures/network-watchguard-snmp.md
Labels: area/connectors

#2944 Refresh the network-dell-sseries-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dell-sseries-snmp.md
  pp/integrations/plugin-packs/procedures/network-dell-sseries-snmp.md
Labels: area/connectors

#2782 Refresh the Mikrotik documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-mikrotik-snmp.md
  pp/integrations/plugin-packs/procedures/network-mikrotik-snmp.md
Labels: area/connectors

#3100 [HA] Make commands consistent
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha/installation-4-nodes.md
  versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md
  versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md
  versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md
  versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
  versioned_docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md
  versioned_docs/version-24.04/installation/installation-of-centreon-ha/installation-4-nodes.md
Labels: HA

#3047 Mon 17987 enh ha upgrade to 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/centreon-ha/upgrade-from-22-04.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/centreon-ha/upgrade-from-22-10.md
  versioned_docs/version-23.04/upgrade/centreon-ha/upgrade-from-22-04.md
  versioned_docs/version-23.04/upgrade/centreon-ha/upgrade-from-22-10.md
Labels: HA

#3142 doc(release): Prepare release notes for OSS 22.04
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
  versioned_docs/version-22.04/releases/centreon-core.md
Labels: release-notes

#3141 doc(release): Prepare release notes for OSS 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#3140 doc(release): prepare release notes for OSS 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3135 doc(release): prepare release notes for OSS 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#3133 doc(release): prepare release notes for Modules 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3138 doc(release): prepare release notes for Modules 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3125 enh(mc): automatic commit for network-ruckus-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ruckus-snmp.md
  pp/integrations/plugin-packs/procedures/network-ruckus-snmp.md
Labels: area/connectors

#3119 enh(mc): automatic commit for network-ubiquiti-unifi-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ubiquiti-unifi-snmp.md
  pp/integrations/plugin-packs/procedures/network-ubiquiti-unifi-snmp.md
Labels: area/connectors

#3129 enh(mc): automatic commit for network-switchs-juniper-ex-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
Labels: area/connectors

#3127 enh(mc): automatic commit for network-firewalls-sonicwall-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-sonicwall-snmp.md
  pp/integrations/plugin-packs/procedures/network-firewalls-sonicwall-snmp.md
Labels: area/connectors

#3126 enh(mc): automatic commit for network-3com-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-3com-snmp.md
  pp/integrations/plugin-packs/procedures/network-3com-snmp.md
Labels: area/connectors

#3123 enh(mc): automatic commit for network-hp-vc-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-vc-snmp.md
  pp/integrations/plugin-packs/procedures/network-hp-vc-snmp.md
Labels: area/connectors

#3124 enh(mc): automatic commit for network-routers-juniper-mseries-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
  pp/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
Labels: area/connectors

#3122 enh(mc): automatic commit for network-fortinet-fortiweb-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiweb-snmp.md
  pp/integrations/plugin-packs/procedures/network-fortinet-fortiweb-snmp.md
Labels: area/connectors

#3120 enh(mc): automatic commit for network-dlink-standard-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dlink-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-dlink-standard-snmp.md
Labels: area/connectors

#3121 enh(mc): automatic commit for network-fortinet-fortiswitch-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiswitch-snmp.md
  pp/integrations/plugin-packs/procedures/network-fortinet-fortiswitch-snmp.md
Labels: area/connectors

#3158 doc(release): add release notes for collect 23.04.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3159 doc(release): add release notes for collect 23.10.5
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#3160 doc(release): Fix collect 23.04.10 release notes.
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3118 enh(mc): automatic commit for network-digi-anywhereusb-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-digi-anywhereusb-snmp.md
  pp/integrations/plugin-packs/procedures/network-digi-anywhereusb-snmp.md
Labels: area/connectors

#3156 The customer is responsible for the poller
  cloud/installation/poller-secure.md
  cloud/installation/poller-update-upgrade.md
  cloud/installation/prerequisites.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-secure.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-update-upgrade.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md
Labels: cloud

#3166 fix(rn): an item was missing from february release notes
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#3093 Enh ha installation el9
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md
  versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md
  versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
  versioned_docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md
Labels: HA

#3113 enh(mc): automatic commit - Open LDAP
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-openldap-ldap.md
  pp/integrations/plugin-packs/procedures/applications-openldap-ldap.md
Labels: area/connectors

#3114 enh(mc): automatic commit - Cisco SSMS REST API
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-cisco-ssms-restapi.md
  pp/integrations/plugin-packs/procedures/applications-cisco-ssms-restapi.md
Labels: area/connectors

#3117 enh(mc): automatic commit for network-cisco-wap-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
Labels: area/connectors

#3018 [Cloud] Change update and upgrade procedures
  cloud/installation/poller-secure.md
  cloud/installation/poller-update-upgrade.md
  cloud/installation/poller-update.md
  cloud/installation/poller-upgrade.md
  cloud/installation/prerequisites.md
  cloud/sidebarsCloud.js
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-secure.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-update-upgrade.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-update.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-upgrade.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md
Labels: cloud

#3178 doc(release): prepare release notes for OSS 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3179 doc(release): prepare release notes for OSS 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#3180 doc(release): Prepare release notes for OSS 22.04
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
  versioned_docs/version-22.04/releases/centreon-core.md
Labels: release-notes

#3177 doc(release): prepare release notes for OSS 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes
