Repository centreon/centreon-documentation, pull requests merged in 2024-06, with the labels that each got.

#3304 [CTOR-568] Create Grafana doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-grafana-api.md
  pp/integrations/plugin-packs/procedures/applications-grafana-api.md
  pp/sidebarsPp.js
Labels: area/connectors

#3317 [CTOR-610] Refresh Veeam doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-nrpe.md
  pp/integrations/plugin-packs/procedures/applications-veeam-nrpe.md
Labels: area/connectors

#3302 [CTOR-487] Update the DNS Service doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-dns.md
  pp/integrations/plugin-packs/procedures/applications-protocol-dns.md
Labels: area/connectors

#3314 enhance(documentation) CTOR-591 Trendmicro IWSVA packaging
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-trendmicro-iwsva-snmp.md
  pp/integrations/plugin-packs/procedures/applications-trendmicro-iwsva-snmp.md
Labels: area/connectors

#3318 [CTOR-590] update Kadiska doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md
Labels: area/connectors

#3320 doc(release): Release notes for modules 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3346 CTOR-633 : plugin(storage::datacore::restapi) : Add little fixes and enhancements
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
  pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
Labels: area/connectors

#3354 new(mc): added new telegraf connector
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-telegraf-agent.md
  pp/integrations/plugin-packs/procedures/operatingsystems-windows-telegraf-agent.md
  pp/sidebarsPp.js
Labels: area/connectors

#3355 enh(mc): added the collection mode + minor enhancements
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-http.md
  pp/integrations/plugin-packs/procedures/applications-protocol-http.md
Labels: area/connectors

#3338 [CTOR-569] Rename Salesforce doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-salesforce-restapi.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-salesforces-restapi.md
  pp/integrations/plugin-packs/procedures/applications-salesforce-restapi.md
  pp/integrations/plugin-packs/procedures/applications-salesforces-restapi.md
Labels: area/connectors

#3341 [CTOR-608] refresh SMTP Server doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-smtp.md
  pp/integrations/plugin-packs/procedures/applications-protocol-smtp.md
Labels: area/connectors

#3329 doc(release): Release notes for modules 24.04
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3367 CTOR-374-mosquitto-mqtt-broker
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-eclipse-mosquitto-mqtt.md
  pp/integrations/plugin-packs/procedures/applications-eclipse-mosquitto-mqtt.md
  pp/sidebarsPp.js
Labels: area/connectors

#3372 doc(release): prepare release notes for collect 24.04.2
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#3358 June Connectors Release note
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#3301 [CTOR-571] Create Symbol WiNG SNMP doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-symbol-wing-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-symbol-wing-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-symbol-wing-snmp.md
  pp/integrations/plugin-packs/procedures/network-symbol-wing-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#3340 [CTOR-609] refresh Protocol TCP doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md
  pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
Labels: area/connectors

#3352 [CTOR-620] refresh BGP Protocol SNMP doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-bgp-snmp.md
  pp/integrations/plugin-packs/procedures/applications-protocol-bgp-snmp.md
Labels: area/connectors

#3350 Ctor 619 refresh applications pfsense fauxapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
  pp/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
Labels: area/connectors

#3361 [CTOR-618] refresh Oracle VM Manager API doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-oracle-ovm-api.md
  pp/integrations/plugin-packs/procedures/applications-oracle-ovm-api.md
Labels: area/connectors

#3360 [CTOR-621] refresh OSPF Protocol doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ospf.md
  pp/integrations/plugin-packs/procedures/applications-protocol-ospf.md
Labels: area/connectors

#3374 doc(release): Release notes for collect 23.04.13
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3395 doc(release): Prepare release notes for hotfix map 24.04.2
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3392 [CTOR-613] refresh Gorgone Rest API doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-gorgone-restapi.md
  pp/integrations/plugin-packs/procedures/applications-gorgone-restapi.md
Labels: area/connectors

#3398 enh(mc): updated windows telegraf mc procedure
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-telegraf-agent.md
  pp/integrations/plugin-packs/procedures/operatingsystems-windows-telegraf-agent.md
Labels: area/connectors

#3390 [CTOR-615] refresh Node Exporter linux Metrics doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-linux.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-linux.md
Labels: area/connectors

#3391 [CTOR-614] refresh Keepalived SNMP doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-keepalived-snmp.md
  pp/integrations/plugin-packs/procedures/applications-keepalived-snmp.md
Labels: area/connectors

#3393 [CTOR-612] refresh Informix DB SNMP doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
  pp/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
Labels: area/connectors

#3364 Cloud known issues
  cloud/resources/known-issues.md
  cloud/sidebarsCloud.js
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/known-issues.md
Labels: cloud

#3161 [Cloud] Remove comment about AD notification interface
  cloud/monitoring/anomaly-detection.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/anomaly-detection.md
Labels: cloud

#3330 doc(release): Release notes for cloud 24.05
  cloud/releases/cloud-release-notes.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
Labels: cloud, release-notes

#3326 RAM (Cloud)
  cloud/administration/resource_access.md
  cloud/sidebarsCloud.js
  cloud/users/users.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/administration/resource_access.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/users/users.md
Labels: cloud

#3371 doc(release): Release notes for web 24.04.3 / gorgone 24.04.1
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#3403 doc(release): Release notes for web 23.10.13 / gorgone 23.10.8
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#3404 doc(release): Release notes for web 23.04.19 / gorgone 23.04.15
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3405 doc(release): Release notes for web 22.10.23 / gorgone 22.10.8
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#3375 doc(release): Release notes for collect 22.10.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes
