Repository centreon/centreon-documentation, pull requests merged in 2024-07, with the labels that each got.

#3402 [CTOR-653] refresh Azure Cosmos DB doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-cosmosdb.md
  pp/integrations/plugin-packs/procedures/cloud-azure-database-cosmosdb.md
Labels: area/connectors

#3399 [CTOR-659] refresh Azure SQL Server doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqlserver.md
  pp/integrations/plugin-packs/procedures/cloud-azure-database-sqlserver.md
Labels: area/connectors

#3407 [CTOR-655] refresh Azure Database for MariaDB doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-mariadb.md
  pp/integrations/plugin-packs/procedures/cloud-azure-database-mariadb.md
Labels: area/connectors

#3396 [CTOR-606] refresh LDAP Server doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ldap.md
  pp/integrations/plugin-packs/procedures/applications-protocol-ldap.md
Labels: area/connectors

#3400 [CTOR-602] refresh Microsoft DHCP SNMP doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md
  pp/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md
Labels: area/connectors

#3418 doc(release): Prepare release notes for web 24.04.4
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#3423 doc(release): Prepare release notes for modules 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3421 chore(deps): absorb 24.07 dependabot GitHub Actions updates
  .github/workflows/actionlint.yml
  .github/workflows/archive.yml
  .github/workflows/documentation.yml
Labels: dependencies, gha

#3424 doc(release): Release notes for modules 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
  versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Labels: release-notes

#3422 doc(release): Prepare release notes for modules 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3425 doc(release): Release notes map 24.04.3
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3413 enh(mc): update meraki-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-meraki-restapi.md
  pp/integrations/plugin-packs/procedures/network-cisco-meraki-restapi.md
Labels: area/connectors

#3420 [CTOR-658] refresh Azure SQL Managed Instance doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqlmanagedinstance.md
  pp/integrations/plugin-packs/procedures/cloud-azure-database-sqlmanagedinstance.md
Labels: area/connectors

#3409 [CTOR-654] refresh Azure Elastic Pool doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
  pp/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
Labels: area/connectors

#3427 CTOR-682 : July release note
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#3428 Ctor 682 connectors 24.07
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-meraki-restapi.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-nokia-isam-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-telegraf-agent.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/procedures/network-cisco-meraki-restapi.md
  pp/integrations/plugin-packs/procedures/network-nokia-isam-snmp.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-telegraf-agent.md
  pp/integrations/plugin-packs/releases/release-notes.md
  pp/sidebarsPp.js
Labels: area/connectors

#3415 [CTOR-657] refresh Azure Cache for Redis doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-redis.md
  pp/integrations/plugin-packs/procedures/cloud-azure-database-redis.md
Labels: area/connectors

#3419 [CTOR-646] refresh Cisco UCS doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-cisco-ucs-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-servers-cisco-ucs-snmp.md
Labels: area/connectors

#3434 enh(mc): add linux to telegraf +fixes
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/telegraf.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-telegraf-agent.md
  pp/integrations/plugin-packs/getting-started/how-to-guides/telegraf.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-telegraf-agent.md
  pp/integrations/plugin-packs/procedures/operatingsystems-windows-telegraf-agent.md
Labels: area/connectors

#3438 doc(release): Release notes for collect 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3439 doc(release): Release notes for collect 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#3440 doc(release): Release notes for collect 24.04
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#3445 doc(release): Release notes for OSS 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3446 doc(release): Release notes for OSS 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#3447 doc(release): Release notes for OSS 24.04
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#3436 CTOR-728 Plugin(network::sonus::sbc::snmp) - Mode(cpu) : Unknown option
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
  pp/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
Labels: area/connectors

#3430 Ctor 460 teldat snmp cells radio
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-teldat-snmp.md
  pp/integrations/plugin-packs/procedures/network-teldat-snmp.md
Labels: area/connectors

#3450 doc(release): release notes for collect 24.04
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#3451 fix(mc): removed direct link to packages + trailing spaces
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe4.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe4.md
Labels: area/connectors

#3452 doc(release): Release notes for map 23.04.18 and mbi 23.04.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes
