Repository centreon/centreon-documentation, pull requests merged in 2024-12, with the labels that each got.

#3859 doc(release) Release notes modules 24.04
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3866 doc(release) fixed date in modules 24.04 release notes
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3805 CTOR-1137 : Refresh network-ruckus-icx-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ruckus-icx-snmp.md
  pp/integrations/plugin-packs/procedures/network-ruckus-icx-snmp.md
Labels: area/connectors

#3864 CTOR-851 : Plugin(apps::backup::commvault::commserve::restapi) - Mode(storagepools) : If statement added when $total == 0
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-commvault-commserve-restapi.md
  pp/integrations/plugin-packs/procedures/applications-commvault-commserve-restapi.md
Labels: area/connectors

#3869 doc(release) Release notes Modules 24.10
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3813 CTOR-289 : enh(keysight): add ports mode and add license mode
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-keysight-nvos-restapi.md
  pp/integrations/plugin-packs/procedures/network-keysight-nvos-restapi.md
Labels: area/connectors

#3876 doc(release): Release notes open tickets 24.10.2
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx
  versioned_docs/version-24.10/releases/centreon-os.mdx
Labels: release-notes

#3875 doc(release) Release notes open tickets 24.04.3
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#3874 doc(release) Release notes open tickets 23.10.2
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#3873 doc(release) Release notes for open tickets 23.04.5
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3878 CTOR-1221 : Doc(hardware-storage-dell-compellent-api) : Dead link
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-api.md
  pp/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-api.md
Labels: area/connectors

#3872 doc(release) Release notes open tickets 22.10.5
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#3853 CTOR-811 - New JMeter monitoring connector
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-jmeter.md
  pp/integrations/plugin-packs/procedures/applications-jmeter.md
  pp/sidebarsPp.js
Labels: area/connectors

#3856 CTOR-454 : New Plugin(apps::antivirus::skyhigh::webgateway::snmp)
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-antivirus-mcafee-webgateway-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-antivirus-skyhigh-webgateway-snmp.md
  pp/integrations/plugin-packs/procedures/applications-antivirus-mcafee-webgateway-snmp.md
  pp/integrations/plugin-packs/procedures/applications-antivirus-skyhigh-webgateway-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#3863 CTOR-723 : Plugin(network::hp::procurve::snmp) : New mode stack
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-hp-procurve-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-hp-procurve-snmp.md
Labels: area/connectors

#3881 doc(release) Release notes for itee 24.10.2
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3880 CTOR 797 - NewAppearTV monitoring connector
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-video-appeartv-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-devices-video-appeartv-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#3858 CTOR-724 : Plugin(network::nokia::timos::snmp) : New mode sas-alarm
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-nokia-timos-snmp.md
  pp/integrations/plugin-packs/procedures/network-nokia-timos-snmp.md
Labels: area/connectors

#3868 CTOR-1022 : Pack(operatingsystems-windows-centreon-monitoring-agent) : Add native checks
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
  pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
Labels: area/connectors

#3896 doc(release) Release notes modules 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
  versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Labels: release-notes

#3898 Known issues Cloud 24.11
  cloud/resources/known-issues.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/known-issues.md
Labels: cloud

#3897 Doc(release) Release notes cloud 24.11
  cloud/releases/cloud-release-notes.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
Labels: cloud

#3836 CTOR-1187 : Doc(sc-splunk-events) : Fix custom events format in FR
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/data-analytics/sc-splunk-events.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/data-analytics/sc-splunk-events.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-splunk-events.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-splunk-events.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/data-analytics/sc-splunk-events.md
  i18n/fr/docusaurus-plugin-content-docs/version-25.10/integrations/data-analytics/sc-splunk-events.md
Labels: area/connectors

#3841 CTOR-1146 : Refresh network-ubiquiti-edge-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ubiquiti-edge-snmp.md
  pp/integrations/plugin-packs/procedures/network-ubiquiti-edge-snmp.md
Labels: area/connectors

#3842 CTOR-1147 : Refresh network-vectra-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-vectra-restapi.md
  pp/integrations/plugin-packs/procedures/network-vectra-restapi.md
Labels: area/connectors

#3847 CTOR-1150 : Refresh network-viptela-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-viptela-snmp.md
  pp/integrations/plugin-packs/procedures/network-viptela-snmp.md
Labels: area/connectors

#3848 CTOR-1153 : Refresh cloud-cloudfoundry-api
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
  pp/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
Labels: area/connectors

#3849 CTOR-1154 : Refresh cloud-ibm-softlayer-api
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-ibm-softlayer-api.md
  pp/integrations/plugin-packs/procedures/cloud-ibm-softlayer-api.md
Labels: area/connectors

#3865 CTOR-1199 : Java version for operatingsystems-as400-connector
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md
  pp/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md
Labels: area/connectors

#3904 CTOR-1100: Change SAP Hana doc repertory
  pp/sidebarsPp.js
Labels: area/connectors

#3850 CTOR-1075 : Doc(operatingsystems-linux-snmp) : Add troubleshooting section for snmp uptime issue
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
  pp/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
Labels: area/connectors

#3910 doc(release) Release notes for collect 24.10.3 / Gorgone 24.10.2
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx
  versioned_docs/version-24.10/releases/centreon-os.mdx
Labels: release-notes

#3912 doc(release) Release notes collect 24.04.8 / gorgone 24.04.5
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#3917 doc(release) Release notes collect 23.10.13
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#3918 doc(release) Release notes collect 23.04.17
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3839 CTOR-1144 : Refresh network-oracle-otd-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-oracle-otd-snmp.md
  pp/integrations/plugin-packs/procedures/network-oracle-otd-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#3843 CTOR-1148 : Refresh network-versa-director-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-versa-director-restapi.md
  pp/integrations/plugin-packs/procedures/network-versa-director-restapi.md
Labels: area/connectors

#3922 doc(release) correction titre centreon web
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx
Labels: release-notes

#3921 doc(release) Release notes web 24.04.9
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#3919 doc(release) Release notes for web 24.10.3
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx
  versioned_docs/version-24.10/releases/centreon-os.mdx
Labels: release-notes
