Repository centreon/centreon-documentation, pull requests merged in 2024-09, with the labels that each got.

#3513 CTOR-629 : Fix interface example commands
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-3com-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-adva-fsp3000-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-ironport-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dell-sseries-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-digi-anywhereusb-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-extreme-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-checkpoint-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-cisco-asa-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-juniper-mag-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-stonesoft.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiswitch-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-standard-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-vc-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-huawei-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-juniper-isg-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ruckus-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-aruba-standard-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-brocade-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-cisco-smallbusiness-standard-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-dell-xseries-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-hp-procurve-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-mrv-optiswitch-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-watchguard-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-zyxel-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-qnap-snmp.md
  pp/integrations/plugin-packs/procedures/network-3com-snmp.md
  pp/integrations/plugin-packs/procedures/network-adva-fsp3000-snmp.md
  pp/integrations/plugin-packs/procedures/network-cisco-ironport-snmp.md
  pp/integrations/plugin-packs/procedures/network-dell-sseries-snmp.md
  pp/integrations/plugin-packs/procedures/network-digi-anywhereusb-snmp.md
  pp/integrations/plugin-packs/procedures/network-extreme-snmp.md
  pp/integrations/plugin-packs/procedures/network-firewalls-checkpoint-snmp.md
  pp/integrations/plugin-packs/procedures/network-firewalls-cisco-asa-snmp.md
  pp/integrations/plugin-packs/procedures/network-firewalls-juniper-mag-snmp.md
  pp/integrations/plugin-packs/procedures/network-firewalls-stonesoft.md
  pp/integrations/plugin-packs/procedures/network-fortinet-fortiswitch-snmp.md
  pp/integrations/plugin-packs/procedures/network-hp-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-hp-vc-snmp.md
  pp/integrations/plugin-packs/procedures/network-huawei-snmp.md
  pp/integrations/plugin-packs/procedures/network-juniper-isg-snmp.md
  pp/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
  pp/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
  pp/integrations/plugin-packs/procedures/network-ruckus-snmp.md
  pp/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-aruba-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-brocade-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-cisco-smallbusiness-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-dell-xseries-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-hp-procurve-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-mrv-optiswitch-snmp.md
  pp/integrations/plugin-packs/procedures/network-watchguard-snmp.md
  pp/integrations/plugin-packs/procedures/network-zyxel-snmp.md
Labels: area/connectors

#3538 CTOR-735 : Refresh infrastructure-active-directory-nrpe
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/infrastructure-active-directory-nrpe.md
  pp/integrations/plugin-packs/procedures/infrastructure-active-directory-nrpe.md
Labels: area/connectors

#3542 Add release note for september
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#3521 CTOR-868 : Refresh virtualization-hyperv-2012-nrpe
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-hyperv-2012-nrpe.md
  pp/integrations/plugin-packs/procedures/virtualization-hyperv-2012-nrpe.md
Labels: area/connectors

#3520 CTOR-869 : Refresh virtualization-hyperv-nscp-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-hyperv-nscp-restapi.md
  pp/integrations/plugin-packs/procedures/virtualization-hyperv-nscp-restapi.md
Labels: area/connectors

#3544 Backbox quick fix
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/procedures/network-backbox-restapi.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#3554 doc(release) Release notes collect 22.10.11 gorgone 22.10.9
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#3557 Stream connectors 24.09 Release Note
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/stream-connectors.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/stream-connectors.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/stream-connectors.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/stream-connectors.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/stream-connectors.md
  versioned_docs/version-22.10/integrations/stream-connectors.md
  versioned_docs/version-23.04/integrations/stream-connectors.md
  versioned_docs/version-23.10/integrations/stream-connectors.md
  versioned_docs/version-24.04/integrations/stream-connectors.md
  versioned_docs/version-24.10/integrations/stream-connectors.md
Labels: area/connectors

#3504 CTOR-445 : Document InfluxDB SC in official documentation
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
  versioned_docs/version-24.04/integrations/data-analytics/sc-influxdb2-metrics.md
  versioned_sidebars/version-24.04-sidebars.json
Labels: area/connectors

#3558 CTOR-445 : Document InfluxDB SC
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/data-analytics/sc-influxdb2-metrics.md
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/stream-connectors.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/data-analytics/sc-influxdb2-metrics.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/stream-connectors.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-influxdb2-metrics.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/stream-connectors.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/stream-connectors.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/data-analytics/sc-influxdb2-metrics.md
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/stream-connectors.md
  versioned_docs/version-22.10/integrations/data-analytics/sc-influxdb2-metrics.md
  versioned_docs/version-22.10/integrations/stream-connectors.md
  versioned_docs/version-23.04/integrations/data-analytics/sc-influxdb2-metrics.md
  versioned_docs/version-23.04/integrations/stream-connectors.md
  versioned_docs/version-23.10/integrations/data-analytics/sc-influxdb2-metrics.md
  versioned_docs/version-23.10/integrations/stream-connectors.md
  versioned_docs/version-24.04/integrations/stream-connectors.md
  versioned_docs/version-24.10/integrations/data-analytics/sc-influxdb2-metrics.md
  versioned_docs/version-24.10/integrations/stream-connectors.md
  versioned_sidebars/version-22.10-sidebars.json
  versioned_sidebars/version-23.04-sidebars.json
  versioned_sidebars/version-23.10-sidebars.json
  versioned_sidebars/version-24.10-sidebars.json
Labels: area/connectors

#3580 Remove Editor from API tokens permission information
  cloud/administration/api_tokens.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/administration/api_tokens.md
Labels: cloud

#3566 CTOR-910 : Refresh operatingsystems-as400-connector
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md
  pp/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md
Labels: area/connectors

#3524 CTOR-731 : Refresh applications-antivirus-clamav-ssh
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
  pp/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
Labels: area/connectors

#3501 CTOR-836 : Refresh hardware-storage-hp-3par-ssh
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hp-3par-ssh.md
  pp/integrations/plugin-packs/procedures/hardware-storage-hp-3par-ssh.md
Labels: area/connectors

#3528 CTOR-736 : Refresh hardware-servers-hp-snmp
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md
Labels: area/connectors

#3527 CTOR-850 : Refresh cloud-microsoft-office365-teams
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-teams.md
  pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-teams.md
Labels: area/connectors

#3525 CTOR-848 : Refresh cloud-microsoft-office365-sharepoint
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-sharepoint.md
  pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-sharepoint.md
Labels: area/connectors

#3531 CTOR-867 : Missing permission in cloud-aws-health
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-health.md
  pp/integrations/plugin-packs/procedures/cloud-aws-health.md
Labels: area/connectors

#3532 CTOR-788 : Oracle Database missing informations in perl librairies step
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-oracle.md
  pp/integrations/plugin-packs/procedures/applications-databases-oracle.md
Labels: area/connectors

#3591 doc(release): Release notes collect 24.04.6 / gorgone 24.04.2
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#3585 doc(release): Release notes for web 23.04.22
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes
