Repository centreon/centreon-documentation, pull requests merged in 2024-02, with the labels that each got.

#2685 add info for Red Hat 9
  pp/integrations/plugin-packs/procedures/applications-databases-redis.md
Labels: external

#3008 enh(mc): added the compatibililty information for vmware 6 & 7
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-6.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
  pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md
  pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-6.md
  pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
  pp/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
Labels: area/connectors

#2705 Update operatingsystems-linux-nrpe3.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
Labels: external

#2924 refresh network-firewalls-cisco-asa-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-cisco-asa-snmp.md
  pp/integrations/plugin-packs/procedures/network-firewalls-cisco-asa-snmp.md
Labels: area/connectors

#2933 Refresh network-switchs-cisco-smallbusiness-standard-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-cisco-smallbusiness-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-cisco-smallbusiness-standard-snmp.md
Labels: area/connectors

#2923 refresh the network-firewalls-stonesoft documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-stonesoft.md
  pp/integrations/plugin-packs/procedures/network-firewalls-stonesoft.md
Labels: area/connectors

#3020 doc(release): prepare release notes for Modules 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3023 add(mc): new inmatics sputnik monitoring connector
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-inmatics-sputnik-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-ups-inmatics-sputnik-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#3009 enh(mc): update Azure AKS pack
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
  pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
Labels: area/connectors

#3037 Ctor 8 new map mc
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-map-engine-actuator.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-map-engine-actuator.md
  pp/sidebarsPp.js
Labels: area/connectors

#3038 release(mc): add new release notes
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#2992 [CTOR-96] Rubrik - Enhance jobs and cache modes
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
  pp/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
Labels: area/connectors

#2984 [CTOR-139] [Documentation] Operatingsystems linux local mode systemd sc status not working in RHEL 9
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
  pp/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
Labels: area/connectors

#3039 doc(release): Prepare release notes for oss 22.04
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
  versioned_docs/version-22.04/releases/centreon-core.md
Labels: release-notes

#3042 doc(release): prepare release notes for OSS 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3043 doc(release): Prepare release notes for OSS 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#3044 doc(release): prepare release notes for Collect 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#3046 doc(release): Prepare release notes for collect 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3041 doc(release): Prepare release notes for OSS 22.10
  i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
  versioned_docs/version-22.10/releases/centreon-os.md
Labels: release-notes

#3048 doc(release): prepare release notes for Modules 23.04
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3049 doc(release) prepare release notes for modules 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#2926 Refresh the network-silverpeak-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
  pp/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
Labels: area/connectors

#2925 Refresh the network-routers-redback-snmp documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
  pp/integrations/plugin-packs/procedures/network-routers-redback-snmp.md
Labels: area/connectors

#3062 enh(ci): dependabot configuration
  .github/dependabot.yml
Labels: dependencies, javascript, php

#3060 doc(release): Prepare release notes for Modules 22.04
  i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
  versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
Labels: release-notes

#2951 Update configuration forms (H, HTPL, S, STPL) - Cloud
  cloud/monitoring/basic-objects/hosts-create.md
  cloud/monitoring/basic-objects/hosts-templates.md
  cloud/monitoring/basic-objects/hosts.md
  cloud/monitoring/basic-objects/services-create.md
  cloud/monitoring/basic-objects/services-templates.md
  cloud/monitoring/basic-objects/services.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/hosts-create.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/hosts.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/services-create.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/services-templates.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/services.md
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/basic-objects/hosts.md
Labels: cloud

#3077 Add time periods to Cloud doc
  cloud/monitoring/basic-objects/hosts.md
  cloud/monitoring/basic-objects/timeperiods.md
  cloud/service-mapping/ba-management.md
  cloud/sidebarsCloud.js
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/hosts.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/timeperiods.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/service-mapping/ba-management.md
Labels: cloud

#3083 enh(mc): refresh the procedure for Socomec Net Vision
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-socomec-netvision-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-ups-socomec-netvision-snmp.md
Labels: area/connectors
