Repository centreon/centreon-documentation, pull requests merged in 2025-04, with the labels that each got.

#4020 doc(cloud-azure-classicstorage-storageaccount): refresh documentation CTOR-1302
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-classicstorage-storageaccount.md
  pp/integrations/plugin-packs/procedures/cloud-azure-classicstorage-storageaccount.md
Labels: area/connectors

#4021 doc(operatingsystems-solaris-snmp): refresh doc page CTOR-1305
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-solaris-snmp.md
  pp/integrations/plugin-packs/procedures/operatingsystems-solaris-snmp.md
Labels: area/connectors

#4022 doc(hardware-storage-panzura-snmp): refresh doc page CTOR-1306
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-panzura-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-panzura-snmp.md
Labels: area/connectors

#4023 doc(applications-databases-sybase): refresh doc page CTOR-1303
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-sybase.md
  pp/integrations/plugin-packs/procedures/applications-databases-sybase.md
Labels: area/connectors

#4072 doc(applications-databases-mysql): Quick fixes on Mysql doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mysql.md
  pp/integrations/plugin-packs/procedures/applications-databases-mysql.md
Labels: area/connectors

#4173 enh(network-silverpeak-snmp): added interfaces discovery rule CTOR-256
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
  pp/integrations/plugin-packs/procedures/network-silverpeak-snmp.md
Labels: area/connectors

#4176 doc(hardware-storage-ibm-fs900-snmp): update documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-ibm-fs900-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-ibm-fs900-snmp.md
Labels: area/connectors

#4268 enh(network-loadbalancers-f5-bigip-snmp): added new cpu-usage mode CTOR-427
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-loadbalancers-f5-bigip-snmp.md
  pp/integrations/plugin-packs/procedures/network-loadbalancers-f5-bigip-snmp.md
Labels: area/connectors

#4256 enh(hardware::ups::apc::snmp) - Mode(battery-status) : Enhance options replace-lasttime
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-apc-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-ups-apc-snmp.md
Labels: area/connectors

#4255 enh(apps::backup::veeam::vbem::restapi): handle replication jobs in jobs mode and service discovery CTOR-1321
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
  pp/integrations/plugin-packs/procedures/applications-veeam-vbem-restapi.md
Labels: area/connectors

#4250 Added the option check-overload in uptime services templates CTOR-1196
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-synology-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortimail-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-viptela-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-hpux-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-synology-snmp.md
  pp/integrations/plugin-packs/procedures/network-fortinet-fortimail-snmp.md
  pp/integrations/plugin-packs/procedures/network-viptela-snmp.md
  pp/integrations/plugin-packs/procedures/operatingsystems-hpux-snmp.md
Labels: area/connectors

#4239 enh(jmeter): add --command-path macro
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-jmeter.md
  pp/integrations/plugin-packs/procedures/applications-jmeter.md
Labels: area/connectors

#4266 feat(mc): new Exense Step monitoring connector
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-exense-step-restapi.md
  pp/integrations/plugin-packs/procedures/applications-exense-step-restapi.md
  pp/sidebarsPp.js
Labels: area/connectors

#4213 enh(vmware8-esx): add 3 new modes + breaking changes to existing ones
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/application-virtualization-vmware8-esx-restapi.md
  pp/integrations/plugin-packs/procedures/application-virtualization-vmware8-esx-restapi.md
Labels: area/connectors

#4238 enh(applications-ibmmq-mqi): Update doc prerequisites with library MQSeries installation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-ibmmq-mqi.md
  pp/integrations/plugin-packs/procedures/applications-ibmmq-mqi.md
Labels: area/connectors

#4107 enh(operatingsystems-windows-centreon-monitoring-agent) : added natives checks cma-health and services CTOR-1413
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
  pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
Labels: area/connectors

#4273 Connectors release 25.04 - release note
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#4279 Quick fix on release note 25.04
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#4086 [CTOR-1351]-Refresh cloud-azure-compute-vmscalesets doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-vmscalesets.md
  pp/integrations/plugin-packs/procedures/cloud-azure-compute-vmscalesets.md
Labels: area/connectors

#4080 [CTOR-1350]-Refresh cloud-azure-compute-virtualmachine doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-virtualmachine.md
  pp/integrations/plugin-packs/procedures/cloud-azure-compute-virtualmachine.md
Labels: area/connectors

#4079 [CTOR-1349]-Refresh cloud-azure-analytics-eventhubs doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-analytics-eventhubs.md
  pp/integrations/plugin-packs/procedures/cloud-azure-analytics-eventhubs.md
Labels: area/connectors

#4088 [CTOR-1353]-Refresh cloud-azure-integration-eventgrid doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-integration-eventgrid.md
  pp/integrations/plugin-packs/procedures/cloud-azure-integration-eventgrid.md
Labels: area/connectors

#4036 doc(virtualization-proxmox-ve-restapi): Refresh documentation page CTOR-1336
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-proxmox-ve-restapi.md
  pp/integrations/plugin-packs/procedures/virtualization-proxmox-ve-restapi.md
Labels: area/connectors

#4282 Doc(release) Release notes collect 23.10.15
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#4260 chore(deps): absorb 2025-04 dependabot GitHub Actions updates
  .github/workflows/archive.yml
  .github/workflows/documentation.yml
Labels: dependencies, gha

#4285 doc(release): Prepare release notes for collect 24.04.11
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#4286 doc(release) release notes collect 24.10.6
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx
  versioned_docs/version-24.10/releases/centreon-os.mdx
Labels: release-notes

#4113 doc(network-aruba-aoscx-snmp): quick fix aruba aoscx
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
  pp/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
Labels: area/connectors

#4134 doc(applications-protocol-http): add collection tutorial link CTOR-1348
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-http.md
  pp/integrations/plugin-packs/procedures/applications-protocol-http.md
Labels: area/connectors

#4085 [CTOR-1304]-Refresh hardware-servers-sun-mgmtcards doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-sun-mgmtcards.md
  pp/integrations/plugin-packs/procedures/hardware-servers-sun-mgmtcards.md
Labels: area/connectors

#4089 [CTOR-1354]-Refresh cloud-azure-integration-service bus doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-integration-servicebus.md
  pp/integrations/plugin-packs/procedures/cloud-azure-integration-servicebus.md
Labels: area/connectors

#4090 [CTOR-1355]-Refresh cloud-azure-management-apimanagement doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-apimanagement.md
  pp/integrations/plugin-packs/procedures/cloud-azure-management-apimanagement.md
Labels: area/connectors

#4091 [CTOR-1356]-Refresh cloud-azure-management-applicationinsights doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-applicationinsights.md
  pp/integrations/plugin-packs/procedures/cloud-azure-management-applicationinsights.md
Labels: area/connectors

#4092 [CTOR-1358]-Refresh cloud-azure-management-insightsmetrics doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-insightsmetrics.md
  pp/integrations/plugin-packs/procedures/cloud-azure-management-insightsmetrics.md
Labels: area/connectors

#4094 [CTOR-1360]-Refresh cloud-azure-management-recovery doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-recovery.md
  pp/integrations/plugin-packs/procedures/cloud-azure-management-recovery.md
Labels: area/connectors

#4095 fix(applications-protocol-x509): fix command line and added custmode description
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-x509.md
  pp/integrations/plugin-packs/procedures/applications-protocol-x509.md
Labels: area/connectors

#4097 [CTOR-1368]-Refresh cloud-azure-network-networkinterface doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-network-networkinterface.md
  pp/integrations/plugin-packs/procedures/cloud-azure-network-networkinterface.md
Labels: area/connectors

#4106 [CTOR-1422]-Refresh cloud-azure-policyinsights-policystates doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
  pp/integrations/plugin-packs/procedures/cloud-azure-policyinsights-policystates.md
Labels: area/connectors

#4104 [CTOR-1420]-Refresh cloud-azure-network-virtualnetwork doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-network-virtualnetwork.md
  pp/integrations/plugin-packs/procedures/cloud-azure-network-virtualnetwork.md
Labels: area/connectors

#4105 [CTOR-1421]-Refresh cloud-azure-network-vpngateway doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-network-vpngateway.md
  pp/integrations/plugin-packs/procedures/cloud-azure-network-vpngateway.md
Labels: area/connectors

#4110 [CTOR-1364]-Refresh cloud-azure-network-expressroute doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-network-expressroute.md
  pp/integrations/plugin-packs/procedures/cloud-azure-network-expressroute.md
Labels: area/connectors

#4115 doc(applications-selenium): refresh documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-selenium.md
  pp/integrations/plugin-packs/procedures/applications-selenium.md
Labels: area/connectors

#4133 doc(applications-activemq-jmx): refresh documentation page CTOR-1444
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-activemq-jmx.md
  pp/integrations/plugin-packs/procedures/applications-activemq-jmx.md
Labels: area/connectors

#4108 [CTOR-1366]-Refresh cloud-azure-network-frontdoor doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-network-frontdoor.md
  pp/integrations/plugin-packs/procedures/cloud-azure-network-frontdoor.md
Labels: area/connectors

#4109 [CTOR-1365]-Refresh cloud-azure-network-firewall doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-network-firewall.md
  pp/integrations/plugin-packs/procedures/cloud-azure-network-firewall.md
Labels: area/connectors

#4297 doc(release) Release notes web 24.10.7
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx
  versioned_docs/version-24.10/releases/centreon-os.mdx
Labels: release-notes

#4299 doc(release) Release notes modules 23.10
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#4301 doc(release) Release notes 23.04 modules
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3939 CTOR-1259: Refresh hardware-servers-hp-ilo-restapi
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-servers-hp-ilo-restapi.md
Labels: area/connectors

#4300 doc(release) Release notes modules 24.04
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#4298 doc(release) Release notes modules 24.10
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes
