Repository centreon/centreon-documentation, pull requests merged in 2025-09, with the labels that each got.

#4183 [CTOR-1483]-Refresh applications-antivirus-kaspersky-snmp doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-antivirus-kaspersky-snmp.md
  pp/integrations/plugin-packs/procedures/applications-antivirus-kaspersky-snmp.md
Labels: area/connectors

#4184 [CTOR-1482]-Refresh applications-active-directory-wsman doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-active-directory-wsman.md
  pp/integrations/plugin-packs/procedures/applications-active-directory-wsman.md
Labels: area/connectors

#4197 [CTOR-1478]-Refresh harware-storage-ibm-ts-2900-snmp doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-ibm-ts2900-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-ibm-ts2900-snmp.md
Labels: area/connectors

#4195 [CTOR-1477]-Refresh applications-weblogic-jmx doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-weblogic-jmx.md
  pp/integrations/plugin-packs/procedures/applications-weblogic-jmx.md
Labels: area/connectors

#4193 [CTOR-1479]-Refresh applications-drbd-ssh doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-drbd-ssh.md
  pp/integrations/plugin-packs/procedures/applications-drbd-ssh.md
Labels: area/connectors

#4203 [CTOR-1362]-Refresh cloud-azure-network-appgateway doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-network-appgateway.md
  pp/integrations/plugin-packs/procedures/cloud-azure-network-appgateway.md
Labels: area/connectors

#4210 [CTOR-1495]-Refresh applications-bind-9-web doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-bind9-web.md
  pp/integrations/plugin-packs/procedures/applications-bind9-web.md
Labels: area/connectors

#4620 fix(applications-veeam-centreon-monitoring-agent): fixed How to checkin the CLI section CTOR-1885
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-centreon-monitoring-agent.md
  pp/integrations/plugin-packs/procedures/applications-veeam-centreon-monitoring-agent.md
Labels: area/connectors

#4652 CTOR-1837: Add missing default values
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-kubernetes-api.md
  pp/integrations/plugin-packs/procedures/cloud-kubernetes-api.md
Labels: area/connectors

#4635 {Cloud] host_down_disable_service_checks
  cloud/alerts-notifications/concepts.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/concepts.md
Labels: cloud

#4634 [Cloud] Reinstalling a poller from scratch
  cloud/installation/deploy-poller.md
  i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md
Labels: cloud

#4608 CTOR-932 Plugin(cloud::vmware::velocloud::restapi) - Mode(list-edges): No entreprise ID
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-vmware-velocloud-restapi.md
  pp/integrations/plugin-packs/procedures/cloud-vmware-velocloud-restapi.md
Labels: area/connectors

#4650 CTOR-761 Plugin(hardware::ups::apc::snmp) - Mode(sensors) : not compatible with APC Galaxy
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-apc-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-ups-apc-snmp.md
Labels: area/connectors

#4623 Refresh storage::netapp::ontap::restapi - CTOR-1439
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-restapi.md
Labels: area/connectors

#4675 add LatenceTech version compatibility section CTOR-1945
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-latencetech-restapi.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-latencetech-restapi.md
Labels: area/connectors

#4678 doc(release) Release notes web 24.04.18 dsm 24.04.7
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#4679 doc(release) added missing title DSM 24.04.7
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#4513 enh(windows-winrm-wsman-tutorial): Add informations about SDDL configuration CTOR-1184
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md
  pp/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md
Labels: area/connectors

#4683 doc(operatingsystems-windows-nsclient-05-nrp): update doc CTOR-660
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
  pp/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
Labels: area/connectors
