Repository centreon/centreon-documentation, pull requests merged in 2025-01, with the labels that each got.

#3935 doc(release) Release notes modules 24.04
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3929 doc(release) Release notes modules 24.10
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3978 doc(release) delete reduntant title
  versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3927 doc(Release) Release notes web 23.04.24
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#3990 doc(release) added missing release note mbi 24.10.2
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3992 doc(release) Release notes modules 23.04 december
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3993 doc(release) release notes modules 23.10 december
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Labels: release-notes

#3906 enh(netapp::ontap::snmp): added uptime packaging, fixed Disk-Failed command, enhanced documenation page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
Labels: area/connectors

#3934 enh(huawei): update standard doc + create wlc pack
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-huawei-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-huawei-wlc-snmp.md
  pp/integrations/plugin-packs/procedures/network-huawei-snmp.md
  pp/integrations/plugin-packs/procedures/network-huawei-wlc-snmp.md
  pp/sidebarsPp.js
Labels: area/connectors

#3931 CTOR-1252: Plugin(hardware::devices::video::axis::snmp) - Mode(components-fan): Fix map fan status - false positive
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-video-axis-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-devices-video-axis-snmp.md
Labels: area/connectors

#3963 fix(stormshield::api): fixed interfaces mode wrong mapped values
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-stormshield-api.md
  pp/integrations/plugin-packs/procedures/network-stormshield-api.md
Labels: area/connectors

#3964 enh(hp::procurve::snmp): added uptime and spanning-tree modes + spanning-tree discovery rule
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-standard-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-hp-procurve-snmp.md
  pp/integrations/plugin-packs/procedures/network-hp-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-switchs-hp-procurve-snmp.md
Labels: area/connectors

#3962 doc(database::informix)
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-informix.md
  pp/integrations/plugin-packs/procedures/applications-databases-informix.md
Labels: area/connectors

#3965 enh(aruba::aoscx::snmp): added new mode stack
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
  pp/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
Labels: area/connectors

#3998 doc(hardware-telephony-avaya-aes-snmp): Refresh documentation
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-telephony-avaya-aes-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-telephony-avaya-aes-snmp.md
Labels: area/connectors

#4001 doc(netapp-ontap-snmp): Added uptime service
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
Labels: area/connectors

#3821 CTOR 1176: Enhance FreeBSD storage - Add default ZFS support
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-freebsd-snmp.md
  pp/integrations/plugin-packs/procedures/operatingsystems-freebsd-snmp.md
Labels: area/connectors

#4002 doc(connectors): 25.01 Release note
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/releases/release-notes.md
Labels: area/connectors

#4005 doc(connectors): January 2025 release
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-informix.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-iplabel-ekara-restapi.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-kvm-adder-aim-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-telephony-avaya-aes-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-meraki-restapi.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-standard-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-huawei-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-huawei-wlc-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-stormshield-api.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-hp-procurve-snmp.md
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
  pp/integrations/plugin-packs/procedures/applications-databases-informix.md
  pp/integrations/plugin-packs/procedures/applications-monitoring-iplabel-ekara-restapi.md
  pp/integrations/plugin-packs/procedures/hardware-kvm-adder-aim-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-servers-lenovo-xcc-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-telephony-avaya-aes-snmp.md
  pp/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
  pp/integrations/plugin-packs/procedures/network-backbox-restapi.md
  pp/integrations/plugin-packs/procedures/network-cisco-meraki-restapi.md
  pp/integrations/plugin-packs/procedures/network-hp-standard-snmp.md
  pp/integrations/plugin-packs/procedures/network-huawei-snmp.md
  pp/integrations/plugin-packs/procedures/network-huawei-wlc-snmp.md
  pp/integrations/plugin-packs/procedures/network-stormshield-api.md
  pp/integrations/plugin-packs/procedures/network-switchs-hp-procurve-snmp.md
  pp/integrations/plugin-packs/releases/release-notes.md
  pp/sidebarsPp.js
Labels: area/connectors

#3968 chore(deps): absorb 25.01 dependabot GitHub Actions updates
  .github/workflows/actionlint.yml
  .github/workflows/archive.yml
  .github/workflows/documentation.yml
Labels: dependencies, gha

#3933 doc(release) add missing Release note web 23.10.4
  i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx
  versioned_docs/version-24.10/releases/centreon-os.mdx
Labels: release-notes

#3891 CTOR-1216 : Doc(applications-protocol-http) Wrong values for THRESHOLDVALUE
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-http.md
  pp/integrations/plugin-packs/procedures/applications-protocol-http.md
Labels: area/connectors

#3907 CTOR:661 - Doc(applications-databases-oracle) : Missing view
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-oracle.md
  pp/integrations/plugin-packs/procedures/applications-databases-oracle.md
Labels: area/connectors

#3911 CTOR-1156: Refresh cloud-prometheus-api
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-prometheus-api.md
  pp/integrations/plugin-packs/procedures/cloud-prometheus-api.md
  pp/sidebarsPp.js
Labels: area/connectors

#3852 CTOR-1198 : Refresh applications-biztalk
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-biztalk.md
  pp/integrations/plugin-packs/procedures/applications-biztalk.md
Labels: area/connectors

#4024 doc(release) added missing RN collect 24.04.8
  i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
  versioned_docs/version-24.04/releases/centreon-os.mdx
Labels: release-notes

#4025 doc(release) Release notes 23.04 OSS january 2025
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
  versioned_docs/version-23.04/releases/centreon-os.mdx
Labels: release-notes

#4026 doc(release) release notes web 23.10.20 - DSM 23.10.2
  i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
  versioned_docs/version-23.10/releases/centreon-os.mdx
Labels: release-notes

#3943 [CTOR-1163]-Refresh hardware-devices-timelinkmicro-tms-6001-snmp doc …
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-timelinkmicro-tms6001-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-devices-timelinkmicro-tms6001-snmp.md
Labels: area/connectors

#3942 [CTOR-1158]-Refresh cloud-prometheus-node-exporter-api doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-prometheus-node-exporter-api.md
  pp/integrations/plugin-packs/procedures/cloud-prometheus-node-exporter-api.md
Labels: area/connectors

#3941 [CTOR-1160]-Refresh hardware-devices-aeg-acm-snmp doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-aeg-acm-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-devices-aeg-acm-snmp.md
Labels: area/connectors

#3938 [CTOR-1161]-Refresh hardware-devices-eltek-enexus-snmp doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-eltek-enexus-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-devices-eltek-enexus-snmp.md
Labels: area/connectors

#3937 [CTOR-1162]-Refresh hardawre-devices-masterclock-ntp100gps-snmp doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-masterclock-ntp100gps-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-devices-masterclock-ntp100gps-snmp.md
Labels: area/connectors

#3936 [CTOR-1159]-Refresh hardware-device-safenet-keysecure-snmp doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-device-safenet-keysecure-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-device-safenet-keysecure-snmp.md
Labels: area/connectors

#3924 [CTOR-1182]-Refresh cloud-azure-management-automation doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-automation.md
  pp/integrations/plugin-packs/procedures/cloud-azure-management-automation.md
Labels: area/connectors

#3945 [CTOR-1168]-Refresh hardware-servers-hp-blade-chassis-snmp doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-blade-chassis-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-servers-hp-blade-chassis-snmp.md
Labels: area/connectors

#3946 [CTOR-1171] Refresh hardware-servers-ibm-bladecenter-snmp doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-ibm-bladecenter-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-servers-ibm-bladecenter-snmp.md
Labels: area/connectors

#3948 [CTOR-1167] Refresh hardware-servers-dell-openmanage-snmp doc page
  i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-dell-openmanage-snmp.md
  pp/integrations/plugin-packs/procedures/hardware-servers-dell-openmanage-snmp.md
Labels: area/connectors

#4030 doc(release) Release notes map 23.04.22
  i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx
  versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Labels: release-notes
